### ISSUE TITLE
Bugs in shadow geometry calculation

### ISSUE THREAD

**Issue by JustinZarb** [architecture-building-systems/hive#1]
The shadow geometry is incorrectly calculated for certain hours

**Comment by JustinZarb** [comment]
The shadow geometry is not correctly calculated for certain hours.

**Comment by pjayathissa** [comment]
Hi @JustinZarb , is this a question for Joan?

**Comment by JustinZarb** [comment]
No, I had to write my own script in ghPython which uses boolean operations, since it doesn't come with Pyclipper (which Joan uses) and I want to stick to default ghpython.
