### ISSUE TITLE
clipper.dll permanent directory

### ISSUE THREAD

**Issue by JustinZarb** [architecture-building-systems/hive#10]
Need to find a universal way to get to the clipper.dll address, both for saved and unsaved Rhino files (os.cwd is different for either of these cases)

**Comment by daren-thomas** [comment]
never use `os.cwd` for finding paths! this depends on _where_ you started the script. instead, you can find the folder including the script like this:

```
src_folder = os.path.dirname(__file__)
```

And then use `os.path.join(...)` to create the paths. You can add relative paths using the `..` special folders to indicate "parent-directory".

**Comment by JustinZarb** [comment]
Thanks for your reply Daren! In my latest commit I made the following change:

[clipper_path = os.getenv('APPDATA')+'\Grasshopper\Libraries\clipper_library.dll'](https://github.com/architecture-building-systems/hive/blob/cad4ea3a15eb9f8b4ede71a77c145e8668ba7d0c/HIVE_RC_simulator/src/Hive_Hive.py#L54)

**Comment by daren-thomas** [comment]
It's a bug: 

- don't concatenate strings to create paths. Use `os.path.join`.
  - actually, I mentioned that above...
- don't use backslashes (without escaping them) in string literals
  - _unless_ you're using the "raw" strings: `r'\Grasshopper\Libraries\clipper_library.dll'`. Note the `r` at the beginning of the string? This tells python not to view the backslash as an escaping character. You just got lucky here. If any of the characters following the backslash had been one of those used in an escape sequence, you would not have gotten the result you expected.
- why didn't you keep the dll relative to the script? now it's harder to install your software, as you can't just "copy paste". also, you now have to figure out how to package it when publishing for `pip install`.
- your code is now hardcoded to look for the dll in the user's APPDATA folder - that means, it is now not possible to install the software for all users. This is a mistake I have made too with my RPS software.

The line should read:

```
clipper_path = os.path.join(os.getenv('APPDATA'), 'Grasshopper', 'Libraries', 'clipper_library.dll')
```
