### ISSUE TITLE
Database for SIA2024 and SIA2028

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#111]
Get a student to copy all the data from SIA2024 (room and occupant parameters for different room/building types) and SIA2028 (weather data for different weather stations in Switzerland).

Should be saved in a .csv, or .dat, or something.

Is it possible to compile that data file into the component.py that uses this data, so the .py file doesn't always have to use an text-file-import function to load in the data @daren-thomas ?

 - [x] sia 2024 data done: https://github.com/architecture-building-systems/hive/commit/1ca0c890046142a9581a90e4599afadffc1379e6
- [ ] sia 2028: Script that generates SIA2028 formatted data from EPW data. Assignee @amraladdin ; fyi: @Linwal is also working on sth related. Coordinate with him

**Comment by christophwaibel** [comment]
Excel files exist, but cost money. Klimadaten SIA 2028 cost 3000,- CHF and SIA2024 Raumdatenblätter cost 100,- per year...

Let's just manually type it in?!

http://www.energytools.ch/index.php/de/downloads/datenbanken/category/4-datenbanken
http://www.energytools.ch/index.php/de/downloads/tools/download/2-tools/58-raumdatenblaetter

**Comment by christophwaibel** [comment]
![image](https://user-images.githubusercontent.com/21927657/70712880-1a25e100-1ce5-11ea-8ff1-b451e3786706.png)

@daren-thomas do you think this format is OK to be used as .csv inputs in our scripts?

**Comment by daren-thomas** [comment]
@christophwaibel very close! you'll need to add a column header for the first column too... also, I suggest a second column that actually spells out the abbreviations. Otherwise: yes, that's how it would work. It's a good idea to make sure the column names are the same as the input parameters used in the code.

**Comment by christophwaibel** [comment]
Adam Bufacchi working on the excel table for SIA 2024 now

**Comment by christophwaibel** [comment]
sia 2024 data done: https://github.com/architecture-building-systems/hive/commit/1ca0c890046142a9581a90e4599afadffc1379e6

**Comment by christophwaibel** [comment]
noice @daren-thomas :)
![image](https://user-images.githubusercontent.com/21927657/72979441-9d544f80-3dd8-11ea-801a-7c792010d12c.png)

so here's the thing, in SIA2024 there is "standard", "ideal" and "existing". What do you think would be the best way to implement that into Hive? Making three separate room selector components? Or making a super long list?

Shall we have a look together at this branch @daren-thomas ? https://github.com/architecture-building-systems/hive/tree/111-Database-SIA-2024-and-2028

**Comment by daren-thomas** [comment]
dude! that's brilliant: three separate room selector components!!!!

**Comment by christophwaibel** [comment]
> dude! that's brilliant: three separate room selector components!!!!

not really. we're cluttering the grasshopper canvas with tons of little components :-P
hopefully, that's all going to be hidden with the _mothercell_

**Comment by ChrisZenhub** [comment]
hardcode the monthly weather data ghpython script into a proper honey-badger component.

that ghpython script is in the lecture files grasshopper examples:
https://moodle-app2.let.ethz.ch/mod/folder/view.php?id=441800

**Comment by ChrisZenhub** [comment]
new issue for writing that monthly average component : #283
