### ISSUE TITLE
User-Studies-with-LET

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#118]
Organize and plan user studies, together with ETH LET (Lehrentwicklung und -technologie).

E.g. design an experiment with 2 (student) groups: 1 experiment group and 1 control group. One group using the tool, one is not. And then making a test how much better (aka energy efficient / sustainable...) their designs are. Or how much more they know.

**Comment by christophwaibel** [comment]
First small study beginning of April? 
With MBS building systems student (~17)
@hillias responsible person for organizing and thinking about the survey/user experiment

**Comment by hillias** [comment]
Met with LET on Tuesday, 21.1. @amraladdin will prepare draft for questionnaire and survey procedure.

**Comment by amraladdin** [comment]
First draft is here:
\\nas22\arch_ita_schlueter\03-Research\01-Projects\26_HIVE\05_Documentation\Questionnaire\20200128_Interviews questions.docx

Missing:
- Checking previous feedback sessions from the EaCSIII Students in the previous years and add some of the questions there:
- Checking the Maschinenbau questionnaire (Which one is that @christophwaibel ? I saw it in the notes, but found many results online)
- Checking references for the Video recording and observation chart (Next. Probably better to be added to a new issue).

**Comment by christophwaibel** [comment]
> * Checking the Maschinenbau questionnaire (Which one is that @christophwaibel ? I saw it in the notes, but found many results online)

Unfortunately, I have no idea. I just noted it down from the meeting. But I think @hillias said he knows it?

**Comment by hillias** [comment]
Not sure, which one you mean. The only I can remember of, are 'concept inventories' (see https://en.wikipedia.org/wiki/Concept_inventory). These are special types of questionaire to do cross comparisons between thousands of students. A famous one has been done within mechanics on 'forces' and I think also on thermodynamics, also at ETH, but I don't think these type of questionaires are relevant for HIVE.

**Comment by ChrisZenhub** [comment]
until the EuKS 2 lecture on the 24th April, we need some kind of feedback sheet / questionnaire on the tools they will try during the lecture

should be anonymous, so they can be totally honest

@amraladdin wait until next week for a draft of this lecture from me

- using edu app
- manage delegates from arno for the app

**Comment by amraladdin** [comment]
Done. I'm a delegate and can prepare the questionnaire and post it to the students.
Next step is to check if Christoph can see the eduApp results from his account.

**Comment by ChrisZenhub** [comment]
@amraladdin need from @Christophwaibel :

- draft of the lecture
- what we want to know from the students
- for hive: what can we already test with the students

**Comment by amraladdin** [comment]
Here are the questions I prepared so far. Please @ChrisZenhub @daren-thomas @hillias let me know if you have any edits/suggestions/additions through this shared Google Doc:
https://docs.google.com/document/d/1OhHLnVz_rrMeXZq7j64RojNEa2NRLCrQwsdqJgRiHnI/edit?usp=sharing

Note: I intentionally made many questions, but the aim is to try and reduce them. I look forward to your comments.

**Comment by christophwaibel** [comment]
hey @amraladdin thanks for the first draft! I made some suggestions to them.
@hillias what do you think? any comments?

**Comment by hillias** [comment]
Added my comments in the google doc. @amraladdin can you set up the questionaire in edu app or on moodle?

**Comment by amraladdin** [comment]
Thanks everyone for your input on the Google Doc and Surveymonkey. Here are the latest news. Please let me know what your opinion is by end of today:
**Option 01: EduApp**
- Advantages: Free. Unlimited surveys. realtime results. anonymous.
- Disadvantages: Not so user friendly. Contains bugs that we don't know when will be solved. e.g. questions don't show. See image below:
![image](https://user-images.githubusercontent.com/16256867/79850473-4b659a80-83c4-11ea-9ce4-33ba9f93760d.png)
Although the question is written:
![image](https://user-images.githubusercontent.com/16256867/79850514-5a4c4d00-83c4-11ea-928f-e19a9d60a6d6.png)
Their reply
![image](https://user-images.githubusercontent.com/16256867/79851151-3806ff00-83c5-11ea-9f1c-1a54e128be9b.png)
However, they mentioned that the students would be able to see the questions. We have no way to test this though.
Finally, to write questions 2, 7 and 9, we'll need to write each sub-point in one question.

**Option 02: Surveymonkey**
- Advantages: Free version is easy to use. much more user friendly. anonymous.
- Disadvantages: Limited to 40 responses per survey. To get Likert questions (e.g. Q2, 7 or 9), we need to pay for a full version (47 CHF per month).

**TO SUMMERIZE**
@ChrisZenhub @hillias . I need your opinion here. We either:
- Use EduApp. I'll try to ask to get student access to see if the questions do appear. Then I'll reduce the sub-points under questions 2, 7 and 9 to only 4 points and write each in a question.
or
- We pay 47 CHF for one month on Surveymonkey and save some time and hassle.

**Comment by christophwaibel** [comment]
@amraladdin I would say go with Surveymonkey. @hillias , what do you think?

**Comment by amraladdin** [comment]
Sorry @hillias... I just sent an email to Arno and Valerie asking for the Surveymomkey license by mistake :D I was preparing the email to send later after you answer, but I hit **Send** quickly without thinking.

**Comment by amraladdin** [comment]
@ChrisZenhub @hillias I did not get an answer from Arno or Valerie regarding the payment. If I don't get a reply by tomorrow morning, I'll buy the license anyways and ask for a refund later.

Please let me know if you think otherwise.

**Comment by amraladdin** [comment]
Ok... Finally I'm done... Please check this link and see if the survey works. I'd be happy to get any additional feedback or comments:
https://evaluation-app1.let.ethz.ch/TakeSurvey.aspx?SurveyID=l80L8ol0

**Comment by christophwaibel** [comment]
@amraladdin great, looks amazing! love it

Ok just a detail:
![image](https://user-images.githubusercontent.com/21927657/79977582-cac79c80-849e-11ea-95a4-20f420cf900e.png)

I would take out "attractive" and only say "intuitive". because "attractive" is not very specific, whereas "intuitive" is. The shorter and clearer the questions, the better.
