### ISSUE TITLE
Miscellaneous-Support-Dev

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#124]
- add more shoebox scenarios, parallel/independant of the Mothercell GH_Cluster idea for now 
- get students from MBS build sys class involved to Hive (case studies, coding ,scenarios, documentation, tutorials, exercises...)

**Comment by amraladdin** [comment]
On it.

**Comment by amraladdin** [comment]
we need to plan how we intend to involve the BS students to contribute to hive.
@hillias perhaps we can talk about this?

**Comment by amraladdin** [comment]
we need to plan how we intend to involve the BS students to contribute to hive.
@hillias perhaps we can talk about this?

**Comment by daren-thomas** [comment]
Closing - were moving away from fixed templates.
