### ISSUE TITLE
UI/UX design Windows form for Building Inputs

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#126]
Make a windows form of the Hive.IO.Building input component.
In the windows form, you should be able to set:
- construction (e.g. SIA 2024 pre-sets, or manually set individual constructions)
- internal gains (e.g. SIA 2024 pre-sets, or manual)
- embodied emissions of building elements (pre-set from datasat, or manual)
- construction cost of building elements (pre-set from dataset, or manual).

The Hive.IO.Building component furthermore reads in: 
- geometry of the zone
- window surfaces
...which are processed in a script to pre-sort for walls, floor, roof etc. NOT in the MVP: The windows form should have an option to display, which building element has which construction and the user should be able to manually change individual construction. e.g. a north window could be triple glazed, a south window could be set to double glazed.

coding this guy here:
- Hive.IO.GHComponents.GHBuilding.cs @daren-thomas 
- Hive.IO.Building @christophwaibel 

UI design of the windows form @amraladdin

**Comment by christophwaibel** [comment]
Check out Stefan Caravonic's 2D-to-3D-component
@amraladdin pls find link/component and share here

**Comment by amraladdin** [comment]
Found an older version. Still on the search for the last one. Will update when I find it.

[180525_Plan_to_building.zip](https://github.com/architecture-building-systems/hive/files/4096996/180525_Plan_to_building.zip)

**Comment by amraladdin** [comment]
Here's a 3D Environmental cube draft version that I created with the help of an MAS student

[20171016_Environmental Cube.zip](https://github.com/architecture-building-systems/hive/files/4097090/20171016_Environmental.Cube.zip)

**Comment by amraladdin** [comment]
Duplicate issue #78 
@christophwaibel Should I close #78 ?

**Comment by amraladdin** [comment]
Location on the server of the previously uploaded files:
\\nas22.ethz.ch\nas22\arch_ita_schlueter\03-Research\01-Projects\26_HIVE\06_Development\0_Input_Geometry

**Comment by amraladdin** [comment]
Reference from C.Rheinhart:
https://pdfs.semanticscholar.org/9b56/3de126853d39a34724bb96a66d9035999e8d.pdf?_ga=2.45158631.211773704.1580994371-1273972065.1580994371

**OPAQUE**
U-Factor with Film [W/m2-K] 2.9 / 0.35
Partitions Heavy / light
**FENESTRATION**
Window to wall ratio 50%
Glass U-Factor [W/m2-K] 1.96
Glass SHGC 0.69
Glass Visible Transmittance 0.74
Shade Control No
**LIGHTING**
Target Illuminance, zone/core [lux] 300/100
Lighting Control Linear Dimmer
Lighting Energy [W/m2] 5
**EQUIPMENT & OCCUPANCY**
Equipment Gain [W/m2] 12/1.8
Occupancy Density [people/m2] 0.11/0.02
Minimum Fresh Air [l/s-person] 10
Occupancy Schedule, zone/core Office/Circulation
**ENERGY SUPPLY**
COP heating and cooling 1.0/1.0

**Comment by christophwaibel** [comment]
Windows form also includes energy systems, e.g. like the figure in DIN 18599. Clickable individual components to change them (heat pump, radiators, ventilation, ...):
![image](https://user-images.githubusercontent.com/21927657/73938458-97399500-48e7-11ea-9c64-75a3c347f58f.png)

**Comment by amraladdin** [comment]
Is this issue part of the MVP? @christophwaibel

**Comment by christophwaibel** [comment]
> Is this issue part of the MVP? @christophwaibel

yes. but focus on the visualizer in the current sprint.

I need to finish all the Core models related to building simulation first before you can design the buildings input form

**Comment by amraladdin** [comment]
Yeah, sounds great. I was going to suggest the same :)

**Comment by ChrisZenhub** [comment]
@amraladdin our kick off for this is monday, 6th july

**Comment by amraladdin** [comment]
Hello @daren-thomas and @christophwaibel ,
Please see attached a .zip file with the UI Building presentation (in PDF) and customizable component layout (in .gh).

I assigned you both to the issue now, but please feel free to adjust that. Let me know if you have further questions or modifications.

[hive UI Building.zip](https://github.com/architecture-building-systems/hive/files/4953588/hive.UI.Building.zip)

**Comment by ChrisZenhub** [comment]
thanks a lot! I have removed us as assignees, because for coding this form, I made a new issue #328

**Comment by ChrisZenhub** [comment]
closing this as done (UI/UX design)
