### ISSUE TITLE
Visualizer-Component-Grasshopper

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#127]
Conceptualize, Design, and develop/code a visualizer component in Grasshopper.

Programming-architecture to consider: It'll (probably) read in a Hive.IO.Results object, that should contain all kinds of results (LCA, demand, supply, ...). The visualizer component should then have it's own clickable GUI (Windows forms, libraries for plots?) to select the output of interest.

@amraladdin : Could you sketch a visualizer component? What does it need to visualize, output, etc? Monthly plots, daily plots, radiation, demand, costs, etc...? What needs to be coded first?

Coding that component: Me, I guess? Or @daren-thomas ?

https://github.com/architecture-building-systems/hive/blob/master/repository_files/HiveIOGUI.png

**Comment by christophwaibel** [comment]
![image](https://user-images.githubusercontent.com/21927657/72805434-2772ab80-3c53-11ea-8938-71fdcd485289.png)

**Comment by amraladdin** [comment]
On it :)

**Comment by amraladdin** [comment]
Found an older version. Still on the search for the last one. Will update when I find it.

[180525_Plan_to_building.zip](https://github.com/architecture-building-systems/hive/files/4096996/180525_Plan_to_building.zip)

**Comment by christophwaibel** [comment]
luegsch moal: https://www.ubakus.de/thermische-simulation/

des het au visualisierig :)

**Comment by christophwaibel** [comment]
Native Grasshopper components to check out @daren-thomas : 

![image](https://user-images.githubusercontent.com/21927657/73074693-79693a80-3eba-11ea-986f-f584dc3ec89d.png)

![image](https://user-images.githubusercontent.com/21927657/73074743-93a31880-3eba-11ea-97de-b151f418f818.png)

**Comment by christophwaibel** [comment]
that's would be nice too for Hive!
![image](https://user-images.githubusercontent.com/21927657/75548412-7c14fd80-5a2d-11ea-9741-bbe03ca37841.png)

**Comment by daren-thomas** [comment]
As per discussion on PR #155:


-  Bar plot: heating / cooling / dhw demand monthly (12)
-  Bar plot or curve plot: heating / cooling / dhw hourly annual (8760)
- Bar plot or curve plot: electricity demand and PV electricity generation ("solar_gen" in ghpython example script). Monthly (12) and hourly (8760)
- Bar plot for capacities of supply / storage technologies. ("capacity_" in the ghpython example script, and "area_". Note, that the plot needs different axes description for the Y-axis: storage in kWh, supply/conversion tech in kW, and solar tech in m^2)
- Pie chart for supply/conversion technologies ("capacity_hp", "capacity_chp", "capacity_boiler")
- 2 flashy numbers showing "cost_operation" and "emissions_operation"

@christophwaibel note that if you're going to be supplying a `Hive.IO.Results` object, then we don't really need to do the json route and instead have getters for the different time series.

Also, I think it would be easier to have separate "variables" for monthly and hourly heating. A `Hive.IO.Results` object could either provide the monthly results from the simulation data or aggregate the hourly data.

A note on the naming of the variables: The CEA spent a lot of time naming their stuff. Maybe that could be interesting to copy? E.g. https://city-energy-analyst.readthedocs.io/en/latest/how-to-name-variables.html

**Comment by daren-thomas** [comment]
Plot axis needs units.

**Comment by christophwaibel** [comment]
another nice reference: Lunchbox grasshopper tool also has a plot component:

**Comment by christophwaibel** [comment]
just discovered this component from ArchSim (Year Schedule). It looks like he overwrote the native GH Quick Graph component and gave it some axes. maybe also worth investigating @daren-thomas ?

![image](https://user-images.githubusercontent.com/21927657/77109858-f4675100-6a24-11ea-96cd-aa0b666c76fe.png)

**Comment by daren-thomas** [comment]
I think it looks like he just wrote his own plotting library. What do you mean with investigating?

**Comment by daren-thomas** [comment]
I've created separate issues for the remaining plots.
