### ISSUE TITLE
Check-License-Issues

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#128]
we wanna use external grasshopper tools as well (ladybug/honeybee, etc...)

make sure, that everything is ok legally

**Comment by christophwaibel** [comment]
dependecies of Hive:
- [ ] https://github.com/christophwaibel/GH_Solar_V2
- [ ] https://github.com/ladybug-tools/honeybee
- [ ] ...

**Comment by daren-thomas** [comment]
https://opensource.stackexchange.com/questions/1640/if-im-using-a-gpl-3-library-in-my-project-can-i-license-my-project-under-mit-l

This page goes into a discussion about shipping GPL libraries with MIT licenced software. I'm not sure exactly how to proceed yet.

**Comment by christophwaibel** [comment]
> https://opensource.stackexchange.com/questions/1640/if-im-using-a-gpl-3-library-in-my-project-can-i-license-my-project-under-mit-l
> 
> This page goes into a discussion about shipping GPL libraries with MIT licenced software. I'm not sure exactly how to proceed yet.

I can just change my license of `GH_Solar` to MIT...?

**Comment by christophwaibel** [comment]
https://github.com/ladybug-tools/honeybee-legacy/blob/master/License_Honeybee_GPL.txt

honeybee / ladybug also uses GPL. I'd suggest we also transition to GPL for Hive. @daren-thomas what you say?

**Comment by ChrisZenhub** [comment]
Let's discuss this at todays meeting

**Comment by ChrisZenhub** [comment]
changed to GPL 3.0
