### ISSUE TITLE
Databases-Energy-Systems

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#133]
We need databases in the form of .csv files for:
- [ ] PV technologies
- [ ] Performance ratio
- [ ] Solar thermal tech
- [ ] PVT

example files (.txt, because github doestn support csv):

[pv_efficiency.txt](https://github.com/architecture-building-systems/hive/files/4122055/pv_efficiency.txt)
[performance_ratio.txt](https://github.com/architecture-building-systems/hive/files/4122056/performance_ratio.txt)

[st_efficiency.txt](https://github.com/architecture-building-systems/hive/files/4122177/st_efficiency.txt)

**Comment by christophwaibel** [comment]
PV ETH Materialsammlung

http://www.materialarchiv.ch/cms/de/sammlungen/eth-zuerich.html

@Linwal is in contact with them

**Comment by Linwal** [comment]
@christophwaibel  Am I expected to do something?

**Comment by christophwaibel** [comment]
> @christophwaibel Am I expected to do something?

yes, we need database for PV technologies :)

**Comment by Linwal** [comment]
> 
> 
> > @christophwaibel Am I expected to do something?
> 
> yes, we need database for PV technologies :)

So, there is this PV database with almost 25k PV modules. From those, I took the 75% quartile as the "normal" case (to avoid old modules) and the max for the "high" case. I would go with the "normal" case.
(Sample sizes: Polycristalline: 11'411, Monocristalline: 12043, CIGS: 218, CdTe: 111, HIT: 93)

Is this roughly what you were thinking of?

[pv_efficiency-1.txt](https://github.com/architecture-building-systems/hive/files/4171782/pv_efficiency-1.txt)

**Comment by christophwaibel** [comment]
closed as duplicate of #322
