### ISSUE TITLE
GH-Component-Pictos

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#134]
Designing and drawing nice little grasshopper component pictos 

![image](https://user-images.githubusercontent.com/21927657/73263950-f30e6a80-41d1-11ea-970c-853d7c51a4ea.png)

**Comment by christophwaibel** [comment]
make a list of components (with description?) that need a picto already
@christophwaibel

**Comment by christophwaibel** [comment]
how to make icons:

https://www.grasshopper3d.com/forum/topics/about-component-icons

**Comment by maxenceryan** [comment]
Hi Amr + Christoph,

Attached are the first draft of icons, in 24x24px png format and the illustrator file to go with it. I've also taken the liberty to try out a few hive logos in case you want to play with that.
[Hive_icons_files.zip](https://github.com/architecture-building-systems/hive/files/4205272/Hive_icons_files.zip)

vector preview
![image](https://user-images.githubusercontent.com/53180223/74546807-71496b80-4f4b-11ea-986a-71c344d07b53.png)
24x24 px preview:
![image](https://user-images.githubusercontent.com/53180223/74546883-8e7e3a00-4f4b-11ea-955d-c20177120c91.png)

Best,
Max

**Comment by christophwaibel** [comment]
@maxenceryan very nice, I like :) Good idea with the black logos for the simple components and the coloured ones for the time-resolved. The white background is transparent, yes? Let's put them into Grasshopper and then we can see how to improve them.

@daren-thomas How can we implement logos into honey-badger components? Can you show me next week? Cheers!

**Comment by amraladdin** [comment]
Great work @maxenceryan ! Very quick and nice.

A couple of thoughts:
- Have you tried having all the icons with one line thickness instead of having a thicker border? I somehow like it more.
![Artboard 1](https://user-images.githubusercontent.com/16256867/74649936-e5208980-5180-11ea-907d-885b997ffa67.png)
- Are all the fonts the same type and size? Can we make all of them the same size as the ASHP? without bold? I would apply the same to the SIA and EPW logos. What do you think?
- I would strictly keep one color gradient, e.g. the chiller or chiller_tr... I would make them either one tint of the blue you chose, or faded with white (so, no yellow gradient). Same for the rest of the logos.
- The orange and red colors are quite close, so I was wondering if you can make the electricity logos more yellow to differentiate it from the red?

Can you make a couple of samples, including the above comments to see? You don't have to change all the icons, just a few samples?

Very nice! Thanks a lot.

**Comment by maxenceryan** [comment]
Thanks guys :)

@christophwaibel Im not sure if i have rights, but if you'd like i can make a merge request to add an Icons folder to the repository and push the icons directly in there, adhering to the naming convention of the components as per the first comment on this thread. Might then be easier to assign icons via honey badger.

@amraladdin
some comments
- **thinner borders**: agree, i'm curious to see how it would look in grasshopper
- **fonts**: are different sizes, I find the ASHP too small to be readable at the 24x24px scale, so I was trying to keep it larger when possible. If i dont make it bold, there could be antialiasing that makes it too fuzzy to be readable.  But below are a few icons with the same font / non-bold as the ASHP component
![__chiller](https://user-images.githubusercontent.com/53180223/74845014-a29caf80-532e-11ea-9f11-20de42c7171e.png)   ![__ASHP](https://user-images.githubusercontent.com/53180223/74845019-a3354600-532e-11ea-8a8b-ad2e0e69930e.png)   ![__Boiler](https://user-images.githubusercontent.com/53180223/74845020-a3cddc80-532e-11ea-84cd-ce69c5c51950.png)

- **gradients**:  i was just trying to express a chiller using electricity vs in the future, if you were to use absorption chiller, that it would come from heat. But i understand its a bit messy at such a small scale. Below a couple examples with simple gradient. However, for CHP, I imagine you would still need to show both yellow and red as it produces heat and electricity.
- **stronger yellow**: i was going for orange as a pure yellow can be hard to see on the screen, but perhaps it is legible enough.
- **icon border**: i pushed it to the edge as I figured there is already a spacing/margin between component icons in grasshopper and wanted to use as much of the 24x24px as I could. 

in terms of white/transparency, should i make all whites transparent? perhaps with the exception of the epw component, as it may get confused with the sia weather component.

Icons with all changes

![__SIA2024](https://user-images.githubusercontent.com/53180223/74845172-e7c0e180-532e-11ea-82a2-5274b586551a.png)   ![__SIA380 1](https://user-images.githubusercontent.com/53180223/74845169-e7284b00-532e-11ea-8d37-1c59c7e2d20b.png)   ![__EDandDHW](https://user-images.githubusercontent.com/53180223/74845194-ed1e2c00-532e-11ea-9715-d6d118a0ac1d.png)
![__SIA2028](https://user-images.githubusercontent.com/53180223/74845173-e8597800-532e-11ea-9db3-e71ed89938ae.png)   ![__EPWreader](https://user-images.githubusercontent.com/53180223/74845196-ed1e2c00-532e-11ea-9164-6c09a0a6796e.png)
![__SimplePV](https://user-images.githubusercontent.com/53180223/74845180-e98aa500-532e-11ea-9710-6a7b7d334e78.png)   ![__NOCTPV-13](https://user-images.githubusercontent.com/53180223/74845197-edb6c280-532e-11ea-8901-84b69ca3d5d5.png)   ![__SimpleST](https://user-images.githubusercontent.com/53180223/74845181-ea233b80-532e-11ea-8e73-a8e4c10210c8.png)
![__simple-hp](https://user-images.githubusercontent.com/53180223/74845175-e8597800-532e-11ea-9cdf-51210bfc7d1c.png)   ![__simple-hp-tr](https://user-images.githubusercontent.com/53180223/74845178-e98aa500-532e-11ea-84a1-cdcee62db300.png) ![__simple-hp-cop](https://user-images.githubusercontent.com/53180223/74845177-e8f20e80-532e-11ea-8e42-a821ad94256a.png)
![__ASHP](https://user-images.githubusercontent.com/53180223/74845182-ea233b80-532e-11ea-921d-ee795de4bf19.png)   ![__ASHP-tr](https://user-images.githubusercontent.com/53180223/74845183-eabbd200-532e-11ea-9645-1265c210bb18.png)
![__Boiler](https://user-images.githubusercontent.com/53180223/74845184-eabbd200-532e-11ea-92ab-73e66c36abe9.png)   ![__Boiler-tr](https://user-images.githubusercontent.com/53180223/74845185-eb546880-532e-11ea-8046-3683d5c1d398.png)
![__chiller](https://user-images.githubusercontent.com/53180223/74845188-eb546880-532e-11ea-8b0d-5ce02a6dd619.png)   ![__chiller-tr](https://user-images.githubusercontent.com/53180223/74845190-ebecff00-532e-11ea-9dc0-0c0783a4cd93.png)
![__CHP](https://user-images.githubusercontent.com/53180223/74845191-ec859580-532e-11ea-8d9e-fd09c172cc36.png)   ![__CHP-tr](https://user-images.githubusercontent.com/53180223/74845193-ec859580-532e-11ea-9d69-4604a4d879bb.png)

All files: [Icons_02-19.zip](https://github.com/architecture-building-systems/hive/files/4225676/Icons_02-19.zip)

Best,
Max

**Comment by ChrisZenhub** [comment]
@daren-thomas kind reminder that we need icons in Honey-badger

**Comment by daren-thomas** [comment]
![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/3a776616-a513-4e93-bef1-02a1210cf542)

honey-badger can now do icons :)

(this is the first step to addressing this issue)

**Comment by daren-thomas** [comment]
we don't have an icon for sia380_4...
