### ISSUE TITLE
SolarTech-Input-Component

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#142]
**Hive.IO Component, Input Solar Technologies**

Current prototype:
![image](https://user-images.githubusercontent.com/21927657/74724614-c97ab900-523c-11ea-839d-0d3ed5cb2722.png)

Improvements:
- [ ] find pictures for each technology, that we may also use. Right now for prototyping reasons, I used pics from the google, we shouldn't have them in the first release
- [ ] cost and carbon emissions data for PV
- [ ] technology, efficiency, cost, emissions data for solar thermal
- [ ] technology, efficiency, cost, emissions data for PVT
- [ ] technology, efficiency, cost, emissions data for ground solar collectors
- [ ] implement helper text for each technology. maybe even links to technical explanations
- [ ] make the form beautiful
- [ ] deactivate thermal efficiency field when PV radio button is active, electric efficiency for ST and GC

**Comment by Linwal** [comment]
There is a study on the impact of installed PV in CH here [here](http://treeze.ch/fileadmin/user_upload/downloads/Publications/Case_Studies/Energy/Oekobilanz_PV_Batterie_GCGH.pdf). Another possibility could be KBOB data. Otherwise, [this study](https://www.mdpi.com/1996-1073/13/1/252/htm) seems very detailed. 
@christophwaibel What system boundaries are you looking for? Including installation or only the PV module?

**Comment by ChrisZenhub** [comment]
Improve the solar system component:

- UI design: @amraladdin 
- coding the form: @daren-thomas 
- connection to core: @christophwaibel

**Comment by ChrisZenhub** [comment]
from duplicate issue:

A thought to discuss about:
- [ ] Get/create nicer PV images. Perhaps include a sample project.
- [ ] Include a link or more for reference projects. Could be a motivator to see how these components are integrated in cool buildings.

**Comment by hillias** [comment]
For reference objects and nice images see https://solarchitecture.ch/
and https://www.buk.arch.ethz.ch/Solardatenbank/Solardatenbank
The students should be familiar with these references as they form part of our and BUK's lectures.

**Comment by ChrisZenhub** [comment]
duplicate #343
