### ISSUE TITLE
Grasshopper-doesnt-like-json

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#156]
when trying to feed a json string into a grasshopper panel component, it gives following error

![image](https://user-images.githubusercontent.com/21927657/75861220-5dcc4a80-5dfd-11ea-8ce1-2bdbd257f05f.png)

![image](https://user-images.githubusercontent.com/21927657/75861103-31183300-5dfd-11ea-9df2-09665a6236f1.png)

![image](https://user-images.githubusercontent.com/21927657/75861121-383f4100-5dfd-11ea-86f3-e36c237ebe68.png)

**Comment by daren-thomas** [comment]
hm... json might not be the end of the story for us... but it _is_ super weird that a simple string is creating problems... i wonder why?

**Comment by christophwaibel** [comment]
> hm... json might not be the end of the story for us... but it _is_ super weird that a simple string is creating problems... i wonder why?

no problemo with json from the list item component and from c# written jsons (JavaScriptSerializer) tho:
![image](https://user-images.githubusercontent.com/21927657/75889482-4b6a0500-5e2d-11ea-9a29-83e3ef240853.png)

**Comment by daren-thomas** [comment]
@christophwaibel I think this might be Grasshopper trying to be super smart with the output of GHPython components. The list item component declares it's output as string.
