### ISSUE TITLE
Hive_getSimulationData should be renamed to Hive_getWeatherData

### ISSUE THREAD

**Issue by pjayathissa** [architecture-building-systems/hive#16]
I would recommend the following steps

1) Create another catergory called "Environment". "Environment" should exist before "Zone"
2) Rename Hive_getSimulationData to Hive_getWeatherData
3) Move internal gains, and getweather data to the "Environment" catergory

This way only the simulation object exists within the "Simulation Catergory"

**Comment by JustinZarb** [comment]
This is addressed in the next commit.
