### ISSUE TITLE
Hive.IO.Result should probably be an IGOO

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/hive#168]
I'm not quite sure yet how it works, but I think the type of `Hive.IO.Result` should somehow fit into the Grasshopper framework. Right now, passing this into a GhPython component doesn't work, as only a string is received. This would be practical for testing / scripting etc.

I'm guessing after Barcelona @christophwaibel will know much more about this.

**Comment by christophwaibel** [comment]
just found this: https://discourse.mcneel.com/t/setting-a-datatree-gh-curve-type-as-output/69780/2

"...the general recommendation is to use GH_Structure<GH_Goo> in custom components and DataTree in script components..."

**Comment by daren-thomas** [comment]
it doesn't seem relevant?

**Comment by christophwaibel** [comment]
> it doesn't seem relevant?

yeah ok. i wanted to keep GH_Goo as keyword in my leaky memory.

It seems standard practice though to work with custom classes. chec, out Kangarroo solver, which is now shipped with Grasshopper by default:
![image](https://user-images.githubusercontent.com/21927657/76338307-c97c4f00-62f8-11ea-8f1e-a65f7d9e42b3.png)

I got promised to learn how to use custom objects in ghpython components on Friday

**Comment by christophwaibel** [comment]
Ok common way is to just import your library into a ghpython component using `clr`:

```
import clr 

clr.AddReferenceToFileAndPath(r"C:\Users\Chris\AppData\Roaming\Grasshopper\Libraries\Workshop.gha")

from Workshop.CoronaEpidemic import Engine, Person

myPerson = Person(x, 1)

print myPerson.Position
```

@daren-thomas does this answer this issue?

**Comment by daren-thomas** [comment]
@christophwaibel I don't think so - we already had an output of type Hive.IO.Results, but putting that into a ghpython didn't work, right?

**Comment by christophwaibel** [comment]
it does. try in a ghpython component: `print x.TotalElecMonthly`

**Comment by christophwaibel** [comment]
@daren-thomas i'll close it to make our issues list smaller
