### ISSUE TITLE
GHVisualizer should handle missing data more gracefully

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/hive#169]
Place a new GHVisualizer component onto the canvas. Boom:

![image](https://user-images.githubusercontent.com/2969564/76099354-404cdb80-5fcb-11ea-940f-e9008f326a5c.png)

Instead, an empty chart or something should show. Also hooking up to a Hive.IO.Results that is missing, say, cooling or heating demand, should not break rendering.

**Comment by daren-thomas** [comment]
@christophwaibel are you sure this is still an issue? I was not able to reproduce this. Please reproduce the error and post a .gh file I can work on.

**Comment by christophwaibel** [comment]
@daren-thomas it appears if you don't give it heating and cooling and electricity:

![image](https://user-images.githubusercontent.com/21927657/79745050-bc934800-8307-11ea-8fa9-ef420e1c78fb.png)

![image](https://user-images.githubusercontent.com/21927657/79745078-c917a080-8307-11ea-8133-ef846332fb53.png)

**Comment by amraladdin** [comment]
I got the same error today while trying @ChrisZenhub 's Uebungen file for the EuKSII course. When I clicked on the arrow, it showed this:
![image](https://user-images.githubusercontent.com/16256867/79955555-3ef24800-847f-11ea-8fdb-a90ccc9d80b7.png)

Other than the message, I couldn't refresh the results. So I'm wondering @daren-thomas @ChrisZenhub how to refresh the graph so I can get the demand image again?

**Comment by daren-thomas** [comment]
I'm working on it right now!

**Comment by christophwaibel** [comment]
> I got the same error today while trying @ChrisZenhub 's Uebungen file for the EuKSII course. When I clicked on the arrow, it showed this:
> ![image](https://user-images.githubusercontent.com/16256867/79955555-3ef24800-847f-11ea-8fdb-a90ccc9d80b7.png)
> 
> Other than the message, I couldn't refresh the results. So I'm wondering @daren-thomas @ChrisZenhub how to refresh the graph so I can get the demand image again?

oh don't click on the arrows in the Übungen! it only has monthly data anyways!
You can get your old demands back by... deleting the Visualizer component and plugging a new one to the results :) (I think)

**Comment by daren-thomas** [comment]
@christophwaibel check out the PR again: it should now work.
