### ISSUE TITLE
Could you create specific warning messages here

### ISSUE THREAD

**Issue by pjayathissa** [architecture-building-systems/hive#18]
https://github.com/architecture-building-systems/hive/blob/60b3a389506698ef38d85e85638436fafdf706dc/HIVE_RC_simulator/src/Hive_GlazedElement.py#L188

It should ideally have a separate warming message for each of the three missing inputs. Otherwise the user is confused as to what of the many inputs are insufficient

**Comment by ChrisZenhub** [comment]
closed as outdated
