### ISSUE TITLE
discuss-honeybadger-for-Core

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#187]
we should critically discuss the pros and cons of using honeybadger for our simulation core.

pros: 
- python easier for those without scripting experience?

cons:
- not the same full functionality as with .Net grasshopper components
- any new feature (e.g. icons) needs to be implemented by @daren-thomas first. this creates a bottleneck
- iron python

**Comment by ChrisZenhub** [comment]
re-assess after Hive lecture 24th april

**Comment by daren-thomas** [comment]
we decide to stick with honey-badger for Hive.Core.
