### ISSUE TITLE
restructure-Mothercell-folder

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#190]
`Hive.GUI` doesn't need to be a separate solution. It could be another project in the `Hive.IO` solution. And probably needs to be renamed to better describe its purpose, e.g. `Hive.Mothercell`.

The solution can then be renamed to `Hive`, containing projects `Hive.IO` and `Hive.Mothercell`

The simlation core could actually also be another project in the `Hive` solution, named `Hive.Core`

**Comment by ChrisZenhub** [comment]
we've deleted Hive.GUI.

The mothercell could be part of the Hive.IO namespace, depending on how complex of a project that would become
