### ISSUE TITLE
GH Annual Monthly Results Visualization

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#195]
- focuses on the simplified simulations, not the hourly
- designing, how the student would interact with results
- visual design
- storyboard

for Hive v0.3

**Comment by ChrisZenhub** [comment]
@amraladdin, @daren-thomas needs to know how the plots are supposed to look like
- colors
- fonts
- style
- etc

**Comment by amraladdin** [comment]
Shouldn't issue #216 be added to this one?

**Comment by amraladdin** [comment]
Oh, I see... There are a number of smaller issues that you @ChrisZenhub and @daren-thomas created last Thursday. Should this issue then contain the list of visualizations mentioned in the other issues as a checklist? e.g.

[ ] Sankey diagram

**Comment by daren-thomas** [comment]
closing as duplicate.
