### ISSUE TITLE
folder with current build

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#196]
add a folder into the Hive repo that includes the current build (*.gha, *.dll, *.ghpy, etc)

after every sprint

**Comment by ChrisZenhub** [comment]
hey @amraladdin check this out:
https://github.com/architecture-building-systems/hive/releases/tag/v0.2.1

also, you can find some example `.gh` files hidden in the `Source code.zip`, under:

- `.../Mothercell/Hive.IO`
- `.../Core/<subfolder>`

**Comment by amraladdin** [comment]
Hey @ChrisZenhub ,
- Got the files
- downloaded them.
- copied the files in the library
- tested the Hive_01_Shoebox.gh file. GH
- Works like a charm, except the demand part, gives 2 errors:
![image](https://user-images.githubusercontent.com/16256867/78346891-fe9a5b00-759f-11ea-9c6e-1208c0e70249.png)

- tested the clustered version
- Works like a charm

**Comment by christophwaibel** [comment]
@amraladdin yes, don't use the files in /exercise, they are not updated :D

issue made to update /exercise: https://github.com/architecture-building-systems/hive/issues/200
