### ISSUE TITLE
contact sia about our sia tools

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#197]
@Linwal and @daren-thomas have implementation of sia 380.1
also, hive will have one

we could tell SIA to link our tools on their website

**Comment by amraladdin** [comment]
Awaiting their reply.

**Comment by ChrisZenhub** [comment]
let us keep the purpose of contacting SIA for educational use of HIVE.

ideally, they support our tool for education and early-stage design
