### ISSUE TITLE
Inaccurate sun location

### ISSUE THREAD

**Issue by JustinZarb** [architecture-building-systems/hive#2]
The sun altitude and azimuth were slightly different to the Ladybug values for a given HOY and location. This issue has been addressed in a recent commit within the private ASF_Control repository.

[edit: ASF_Control]

**Comment by pjayathissa** [comment]
@JustinZarb , can you please assign the issues to someone so it can be actively worked on?

**Comment by pjayathissa** [comment]
Also, there is no code in this repository? Are you talking about the ASF_Control repo?

**Comment by JustinZarb** [comment]
The code is up now. 
I noticed the problem in Joan's adaptation of your calc_sun_position function, but I spoke to him about it and it has been adressed in the latest push, so now I can fix and test this myself.

**Comment by JustinZarb** [comment]
Joan's updated sun calculations are more accurate, but still vary by around 0.1 degrees with respect to the Ladybug sun
