### ISSUE TITLE
Find Date for GHCluster meeting

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#206]
In our last milestone meeting, we discussed that @daren-thomas will be working more on Hive, specifically taking over the GH Cluster (a.k.a. the "mothercell") task.

We need to find a date for a meeting that works for @Bombyx-ETH, @daren-thomas and @christophwaibel (and @amraladdin ? But I assume it is going to be very programmy-focussed)

Purpose of the meeting:
- learn from Saso, what he has found out so far about the GH Cluster
- information transfer Saso -> Daren
- what is the latest progress, that Saso has achieved regarding the GH Cluster idea?

related issue:
- https://github.com/architecture-building-systems/hive/issues/122

**Comment by ChrisZenhub** [comment]
Dates that work for @daren-thomas : whole last week of April (after 11:00, and preferred Thursday 14:00, before Hive meeting. Not Wednesday morning, Thursday morning)

**Comment by amraladdin** [comment]
I believe it doesn't make sense for me to attend if it'll be programming focused. Would be nice to get a brief afterwards though.

**Comment by christophwaibel** [comment]
> I believe it doesn't make sense for me to attend if it'll be programming focused. Would be nice to get a brief afterwards though.

sure thing!

we found a date: April 30th 15:00-16:00
