### ISSUE TITLE
Building gains & Losses Diagram

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/hive#208]
It might be part of the GHVisualization component - you know, you can click through a carroussel of implemented plots. Maybe this could be one of them?

![image](https://user-images.githubusercontent.com/2969564/79457679-ea6b4a80-7ff0-11ea-8cea-46dc95b651bf.png)

**Comment by amraladdin** [comment]
Great idea @daren-thomas 
What would you expect from me to make this happen?

**Comment by daren-thomas** [comment]
Could you draw a prototype? Basically - what is the visual styling we're going to use for the visualizations? With two architects in the team, leaving visual design decisions to the programmer just seems wrong...

**Comment by christophwaibel** [comment]
the image above is not a Sankey diagram of energy flows. I propose to rename this issue to "Building Gains/Losses Diagram"

**Comment by amraladdin** [comment]
Arno called this diagram a Sankey... Check this out:
![image](https://user-images.githubusercontent.com/16256867/85864220-828d6900-b7c4-11ea-8e8b-a790e2d3af69.png)

**Comment by amraladdin** [comment]
Update: @daren-thomas I changed some of the old names.
See below the new names in _Italic_ and the old name beside them in regular text.
NOTE: All arrows contain a black (RGB = 0, 0, 0) stroke.

_Solar gains_	=	solar heat gains
_Internal gains_ = 	internal heat gains
_Primary energy_ = Primary energy
_Renewable energy_ = Renewable energy
_Electricity (Light + Equipment)_ =	Electricity (light. + syst.)
_Ventilation losses_ = vent. heat losses
_Envelope losses_ =	transm. envelope
_Windows losses_		=	transm. windows
_System Losses_		= System heat losses
_Primary transfer Losses_	= Primary transfer Losses

**See below the RGB colours within the above image:**

NOTE: All arrows contain a black (RGB = 0, 0, 0) stroke.

Gains
Solar gains			=	ffd800
255, 216, 0
Internal gains		= 	b52b28
181, 43, 40
Primary energy	= cc801c
204, 128, 28
Renewable energy	= f29923
242, 153, 35


**Losses**
Electricity (Light + Equipment)	=	3e7c2f
62, 124, 47
Ventilation Losses				=	3b58a6
59, 88, 166
Walls		=	788aa3
120, 138, 163
Windows		=	99b3d6
153, 179, 214
System heat losses		=	856562
133, 101, 99
Primary transfer Losses	= White
255, 255, 255

**Comment by amraladdin** [comment]
Update: I'm removing myself as Assignee from this issue since there's no more work to be done from my side.
