### ISSUE TITLE
Bar plot: heating / cooling / dhw demand monthly (12)

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/hive#209]
The current version of the GHVisualization component only shows heating and cooling. Augment that with domestic hot water. Also, rethink the colours.

**Comment by amraladdin** [comment]
I would add Electricity from lighting and equipment as well. See the below images:
![Slide1](https://user-images.githubusercontent.com/16256867/79872006-81ffdd00-83e5-11ea-8ee4-69b3212dd373.JPG)
![Slide2](https://user-images.githubusercontent.com/16256867/79872014-85936400-83e5-11ea-8b0c-2d70a5e0bc73.JPG)
![Slide3](https://user-images.githubusercontent.com/16256867/79872020-8926eb00-83e5-11ea-9cdf-afdd9de07341.JPG)
![Slide4](https://user-images.githubusercontent.com/16256867/79872032-8c21db80-83e5-11ea-9611-3db4ec25ca53.JPG)
![Slide5](https://user-images.githubusercontent.com/16256867/79872062-9512ad00-83e5-11ea-93f6-754ff51e57e1.JPG)

**Comment by amraladdin** [comment]
@ChrisZenhub which option do you prefer? I prefer option 02 for the Energy and Exergy. The one where the cooling is on the opposite side of the graph.
@daren-thomas would this be something you'd expect from me in the visualization tasks? Or you'll need more information?

**Comment by daren-thomas** [comment]
@amraladdin it's close but it's missing some key information:

- which variant do you want? (seems they're still up for debate)
- what are the exact axis / labels to show?
- what variables (Hive.IO.Results) are being plotted?

**Comment by ChrisZenhub** [comment]
@christophwaibel provide information which variables to plot

**Comment by ChrisZenhub** [comment]
In `Hive.IO.Results`:

        public double[] TotalElectricityMonthly { get; private set; }
        public double[] TotalCoolingMonthly { get; private set; }
        public double[] TotalHeatingMonthly { get; private set; }
        public double[] TotalDHWMonthly { get; private set; }

**Comment by amraladdin** [comment]
@daren-thomas . See answers to your questions below:
__- which variant do you want? (seems they're still up for debate)__
__- what are the exact axis / labels to show?__
See attached PPT:
[Monthly bar chart Design.pptx](https://github.com/architecture-building-systems/hive/files/4591578/Monthly.bar.chart.Design.pptx)

__- What variables (Hive.IO.Results) are being plotted?__
See Christoph's comment above.

__- are these the colors we want? what are they're rgb values?__
RGB values (1st no. = R, 2nd = G, 3rd = B):
**DHW**
192, 0, 0
**Space heating**
255, 0, 0
**Space cooling**
0, 176, 240
**Electricity**
255, 217, 102

__Can you provide an example?_
Yes, see the Excel sheet here:
[Monthly bar chart example.xlsx](https://github.com/architecture-building-systems/hive/files/4591477/Monthly.bar.chart.example.xlsx)
