### ISSUE TITLE
place unit test files within the developer catergory

### ISSUE THREAD

**Issue by pjayathissa** [architecture-building-systems/hive#21]
This way the user can just ignore everything within the 'Developer' catergory and just focus on the simulation

**Comment by JustinZarb** [comment]
I believe this is already the case?

![image](https://user-images.githubusercontent.com/21224625/40689113-17125bb4-63a1-11e8-9d67-4db2f7cc03e1.png)

**Comment by ChrisZenhub** [comment]
closed as outdated
