### ISSUE TITLE
Bar plot or curve plot: heating / cooling / dhw hourly annual (8760)

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/hive#210]
The current GHVisualization component has a rough implementation that has a main drawback:

- it is very slow

I suggest re-creating this as a (possibly down-scaled to the number of pixels available in the GHCapsule?) curve plot.

**Comment by amraladdin** [comment]
Hey @daren-thomas what is the number of pixels available in a GHCapsule?

**Comment by daren-thomas** [comment]
hey @amraladdin great question! as far as I can tell it depends on your screen resolution and the width and height of the capsule. It's not a fixed amount. Any plot designs need to take this into account. We can specify a minimum width and height though. As well as a default one, I think.

**Comment by ChrisZenhub** [comment]
closing as duplicate of #575
