### ISSUE TITLE
2 flashy numbers showing "cost_operation" and "emissions_operation"

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/hive#216]
@christophwaibel please add more information about this

**Comment by christophwaibel** [comment]
![image](https://user-images.githubusercontent.com/21927657/79860001-355ed680-83d2-11ea-8801-b23f03d0e3f2.jpeg)

Something like that. Displaying:
`Results.TotalOpex` and `Results.TotalEmissions` (Not implemented yet)

**Comment by daren-thomas** [comment]
@christophwaibel interesting. I don't understand that plot _at all_. what is it showing? how does it respond to changing data? you have one area that, presumably, is somehow divided up into a blue (opex) and a red (emissions) sub-areas. it looks like roughly half-half. but why? and how do the apples compare to the oranges? I think this needs some more thinking.

**Comment by daren-thomas** [comment]
(i _love_ the sketching style though! that totally works for me. just need to be able to understand what you want...)

**Comment by christophwaibel** [comment]
yes you're right. We need a masterplan of the Visualizer first. How is the interaction with the user, what is clickable, what are the menus... animations... etc..

let's put this issue on hold

**Comment by amraladdin** [comment]
I would suggest we use something very simple for the MVP. See the below example (reference to Climate Studio tool by Solemma)
![image](https://user-images.githubusercontent.com/16256867/83645969-5e6aad80-a5b3-11ea-9af7-aa74e3f97d26.png)

**Comment by amraladdin** [comment]
So, here's the design of the 3 values, from left to right (Energy, Emissions, Costs):
![image](https://user-images.githubusercontent.com/16256867/84909260-bfb37600-b0b5-11ea-9718-cde82db2472e.png)
You should only see one row of values, i.e.:
Totals:
![image](https://user-images.githubusercontent.com/16256867/84910272-f6d65700-b0b6-11ea-9784-277920cde3ee.png)

per m^2:
![image](https://user-images.githubusercontent.com/16256867/84910303-00f85580-b0b7-11ea-9af7-db403bcc459a.png)

Choose to position the units inside the box or outside depending on the overall look. We should try first and see.

I thought it would be great if we can get a nice font. So I got the Barlow font from here:
https://github.com/jpt/barlow
Here is the zipped file of the font:
[Barlow.zip](https://github.com/architecture-building-systems/hive/files/4793095/Barlow.zip)

Here are the two font variations I used. I will leave the size for @daren-thomas to decide:
![image](https://user-images.githubusercontent.com/16256867/84909737-52541500-b0b6-11ea-8239-82bd9d7f3086.png)
RGB numbers as follows:
Emissions: 136, 219, 68
Energy: 144, 153, 40
Costs: 222, 180, 109

would be amazing if we can have it in hive symbols, i.e.:
Total: 
![image](https://user-images.githubusercontent.com/16256867/84910029-ad860780-b0b6-11ea-9d14-d72eb54496fe.png)
per m^2:
![image](https://user-images.githubusercontent.com/16256867/84910078-baa2f680-b0b6-11ea-9dde-57256ee5795b.png)

**Comment by amraladdin** [comment]
@daren-thomas we can see tomorrow if this is sufficient for you or if more information is needed.

**Comment by christophwaibel** [comment]
hey @amraladdin , is it ok if we always write m² instead of m^2? looks a bit better imo

**Comment by amraladdin** [comment]
Hey @christophwaibel Sure! I'm writing it this way so @daren-thomas knows it's meters squared. Not so that it's written that way in the results. If it's confusing, I can change it quickly.
Also, for CO2, the 2 needs to be subscripted.

**Comment by christophwaibel** [comment]
no no, I think you can leave it in these images. maybe, in the next images though you make it precisely how you want it to look like (m²). I'm just saying, because last pull request I asked Daren if he could change a label from m^2 to m² and he referred to your design specs. So just wanted to make sure, that it's also cool with you

**Comment by amraladdin** [comment]
Ah ok, got it. Of course it is cool with me :)

**Comment by amraladdin** [comment]
@christophwaibel I couldn't help it and changed them 👍 Also added the color when any of the values does not reach the benchmark

**Comment by ChrisZenhub** [comment]
@amraladdin design looks good to me!

**Comment by amraladdin** [comment]
Update: I'm removing myself as Assignee from this issue since there's no more work to be done from my side.
