### ISSUE TITLE
subscripts in sia_2024.py in Core doesnt match names in Illias' Excel

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#219]
Illias Excel is here: https://moodle-app2.let.ethz.ch/pluginfile.php/816517/mod_page/content/4/Interaktion%20Struktur%2C%20Klima%20und%20W%C3%A4rmebedarf.xlsx?time=1570794159078

phi_P, G, B, ....

![image](https://user-images.githubusercontent.com/21927657/79701358-bfa51e80-829c-11ea-9f9a-b5f98dd18d8b.png)

**Comment by ChrisZenhub** [comment]
and the hive component has an inconsistency: Phi_G -> should be Phi_A. t_A is already correct

**Comment by daren-thomas** [comment]
stupid question: are we keeping a glossary of abbreviations / variable names? we forgot to do that for the CEA and it was a huge PITA to do afterwards. I guess the students have this information somewhere?

**Comment by christophwaibel** [comment]
> stupid question: are we keeping a glossary of abbreviations / variable names? we forgot to do that for the CEA and it was a huge PITA to do afterwards. I guess the students have this information somewhere?

yeah we can do that, good idea. make a new issue for it. fyi: the components should usually have descriptions for variables, so as a user, just hover over it and it should give a ToolTip

**Comment by ChrisZenhub** [comment]
these hive components will be deprecated soon with issue #248
