### ISSUE TITLE
values in sia2024 room reader don't match with Illias Excel

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#220]
related issue: #219 

![image](https://user-images.githubusercontent.com/21927657/79701403-1b6fa780-829d-11ea-931f-cedfdc35caf9.png)

**Comment by ChrisZenhub** [comment]
agreed with Illias that I'll keep these values in Hive, but for the Excel it might make sense, that he keeps his values. FYI (for future Chris, should he forget all of it):

- beim g-Wert, Reihe 76, sind in der Excel 0.1 eingetragen (SIA: 0.5 für Ziel- und Standardwert, 0.65 für Bestand)

 

                Hier habe ich den kombinierten Wert für g-Wert + Sommerschutz genommen (der ist in der SIA 2024 als 0.1 angegeben). Aber ich sehe, dass dies verwirrend sein kann, da ich es auch g-Wert genannt habe. Sollten wir harmonisieren, evtl. umbennen.

 

- Phi_G (Geräte) heisst eigentlich Phi_A in der SIA 

 

                Habe die Abkürzung eingedeutscht. Soweit ich mich erinnere, war es so auch konsistent mit den verwendeten Abkürzungen in den Vorlesungen. Allerdings müssen die Vorlesungsunterlagen sowieso mit den Gleichungen abgestimmt werden, da vieles nicht mehr stimmt.

 

- Phi_B (Beleuchtung) heisst Phi_L in der SIA

 

                Dito

 

- Volllaststunden (t_L, t_P, t_A) hast du die Tageswerte der SIA verwendet, also t_{P,d}=14.0 h, t_{ud}+t_{un}=7.0 h und t_{A,d}=6.1 h. Diese hast du dann mit 30 multipliziert. Soweit, so gut. Wenn man aber die Jahresvolllaststunden der SIA durch 365 teilt, kommen deutlich niedrigere Wert pro Tag raus (t_L/365 = 4 h, t_A/365 = 4.9 h, und t_P/365=11.2 h. Die Jahresvolllaststunden gehen wohl auch von Wochenenden und Urlaub aus. Da es in der Excel aber um Jahresheizwärmebedarf geht, schlage ich vor die niedrigeren Werte zu nehmen.

 

            Ein guter Punkt, habe ich nie genau angeschaut. Beim Excel geht es ja um beides, Jahreswerte und Monatswerte. Von daher wäre es interessant, ein Profil zu haben um die Unterschiede in den verschiedenen Monaten zu sehen. Dies bedeutet jedoch wiederum eine Verkomplizierung und der Unterschied dürfte in den meisten Fällen sehr gering sein (irrelevant in dieser Phase?). Zudem sind diese Profile meist ja auch sehr grobe Verallgemeinerungen, welche im konkreten Fall dann kaum so genau zutreffen. Die Tageswerte lassen sich halt direkt aus der SIA rauslesen, daher würde ich diese bevorzugen. Vielleicht macht es Sinn, wenn wir eine Bemerkung machen, bzgl. Teillaststunden in den Ferien, Wochenende etc. Wir könnten diesbezüglich auch eine Übung in der Vorlesung machen. Vollaststunden sollte ja jeder mit ein bisschen Intuition auch selber rausfinden können.
