### ISSUE TITLE
g-values dont match Excel and sia2024.py

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#221]
related issues: #219 #220 

![image](https://user-images.githubusercontent.com/21927657/79702735-51198e00-82a7-11ea-8dc1-b672da889cdb.png)

**Comment by christophwaibel** [comment]
U_op and U_w as well

**Comment by ChrisZenhub** [comment]
in the excel, the g-value is combined with shading (as is recommended by SIA), whereas in Hive there is only the g-value from SIA, without shading. So keep it like it is in Hive, but add shading option into the Hive.IO.Buildings form
