### ISSUE TITLE
Internal Gains component is not entirely intuitive

### ISSUE THREAD

**Issue by pjayathissa** [architecture-building-systems/hive#23]
- there is no input for appliance gains which would be useful. It could be a constant
- consider naming the output `occupancy` to `occupancy_profile`
- There is an error possibility if the start and end HOY inputs don't match the weather data inputs
- `custon_pattern` as the first input is a little scary. Can this be moved to the bottom
- Instead of a file path to a csv. Would it be possible to already have a default occupany profile of an Office scenario within the code? Or more ideally, just have a string input to select the occupany profile of choice

**Comment by JustinZarb** [comment]
> 
    there is no input for appliance gains which would be useful. It could be a constant
    consider naming the output occupancy to occupancy_profile
    There is an error possibility if the start and end HOY inputs don't match the weather data inputs
    custon_pattern as the first input is a little scary. Can this be moved to the bottom

These will be addressed in the next commit.
>
    Instead of a file path to a csv. Would it be possible to already have a default occupany profile of an Office scenario within the code? Or more ideally, just have a string input to select the occupany profile of choice.

I would consider implementing some version of the code from the CEA toolbox, which contains a relatively complex model for internal gains https://github.com/architecture-building-systems/CityEnergyAnalyst/blob/master/cea/demand/occupancy_model.py

**Comment by ChrisZenhub** [comment]
closed as outdated
