### ISSUE TITLE
floor_area is an input to `Zone2` is not a required parameter

### ISSUE THREAD

**Issue by pjayathissa** [architecture-building-systems/hive#24]
is this a bug, or is the floor area not used in this component? I thought floor area is a critical component for the simulation

**Comment by JustinZarb** [comment]
This is intentional. by default, the zone components describe a room with the properties of the ASF. 
I agree that it is a potential source of many bugs, but I wanted to discuss this anyway. maybe I can add a general warning if any of the physical properties are not specified.

**Comment by pjayathissa** [comment]
I think this could lead to lots of incorrect results. I would rather the component create an error than create incorrect results.

**Comment by JustinZarb** [comment]
The Zone, floor area and volume are now required inputs
