### ISSUE TITLE
solar.gha and solar.ghpy can only find GHSolar.gha and SolarModel.dll if in root folder

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#245]
i.e. `users\AppData\Roaming\Grasshopper\Libraries\`

make it that it also looks in any subfolders, e.g. if it was in `Libraries\Hive\`, it should also be able to find it

**Comment by daren-thomas** [comment]
this also ties into a whole issue of: how do we deploy?

**Comment by christophwaibel** [comment]
closing as outdated. This was related to some hardcoded path in a honeybadger component
