### ISSUE TITLE
Design a Visualizer masterplan draft

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#247]
**design a tree-diagram or flow-diagram of the Visualizer component**

- how is the component going to look like
- how is the user supposed to interact with it
- what data will it show
- hierarchies of data access? e.g. default display is total performance of the building shown as an Energieausweis. then, user can click on different metrics (emissions, cost, comfort...) and other graphs are shown (monthly energy consumption). Clicking on that again then zooms into hourly resolution... etc.
- how are the graphs going to look like. colors, shape, animations...

**Comment by amraladdin** [comment]
I suggest to break this issue into the following:
- Visualizations mind map draft
- Breakdown issues for each visualization on the map
- Visualizations mind map final

Let me know what you guys think

**Comment by christophwaibel** [comment]
> I suggest to break this issue into the following:
> 
> * Visualizations mind map draft
> * Breakdown issues for each visualization on the map
> * Visualizations mind map final
> 
> Let me know what you guys think

so I thought of this issue to be the "mind map". we can rename it if you like.

"Mind Map Final": is this like an improved version, after the first version exists?

For the individual visualization graphs, yes, let's have separate issues. There are already a bunch of issues existing for Daren. I'd suggest that, first, we have the "mind map", then check with the existing Visualizer issues of Daren and revise them according to your mind map, and add you to Daren's issues. Because each graph is practically a close collaboration between the two of you

**Comment by amraladdin** [comment]
Ah no, then it's perfect :) No need to change the name.
Yes, I agree with the second paragraph as well.

Thanks @christophwaibel

**Comment by amraladdin** [comment]
I've added the small issues to the visualizer mind map (in relation to their corresponding issues on GitHub). See example:
![image](https://user-images.githubusercontent.com/16256867/81397408-89362300-9127-11ea-9d5a-748302ddd797.png)

**Comment by daren-thomas** [comment]
status update: @amraladdin showed us current progress - will place .xmind file in github (should be able to open it in freemind)

**Comment by amraladdin** [comment]
Here's the X-Mind file:
[20200520_hive - design visualizer masterplan.zip](https://github.com/architecture-building-systems/hive/files/4657491/20200520_hive.-.design.visualizer.masterplan.zip)

**Comment by ChrisZenhub** [comment]
@christophwaibel @amraladdin meet up early next week to decide on, from the large mind map, which plots/graphs to do. create separate issues for each graph

**Comment by amraladdin** [comment]
Here's the new version of the masterplan:
[20200601_hive - design visualizer masterplan - Copy.zip](https://github.com/architecture-building-systems/hive/files/4730524/20200601_hive.-.design.visualizer.masterplan.-.Copy.zip)

Next step is to meet up for 2-4 hours (Amr and @christophwaibel ) to:
- decide on which exact graphs/visualization types we want to have (e.g. bar chart, 3D... etc.)
- Begin thinking of the use logic of these visualizations.

**Comment by amraladdin** [comment]
[20200610_hive visualizer masterplan.zip](https://github.com/architecture-building-systems/hive/files/4763376/20200610_hive.visualizer.masterplan.zip)

Latest version. Yesterday Christoph and I checked the Visualization masterplan for the MVP edition.
