### ISSUE TITLE
SIA380.1 component should read separate building elements 

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#248]
...so we can compute individual solar heat gains on each window, individual heat transmission of each wall, roof, etc...

also, so each building can have its own construction (u-value)

**Comment by christophwaibel** [comment]
related issue: #193

**Comment by ChrisZenhub** [comment]
from #193:

check @daren-thomas DPV c# code
also, @Linwal has one in python

**Comment by ChrisZenhub** [comment]
#285
