### ISSUE TITLE
design HIVE icon / logo

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#250]
you can have icons for the tabs in Grasshopper as well! Let's design a hive logo!

![image](https://user-images.githubusercontent.com/21927657/80093949-b00c2b00-8565-11ea-8538-df9db7e20a1b.png)

**Comment by amraladdin** [comment]
![hiveLogo](https://user-images.githubusercontent.com/16256867/82447460-a0bac780-9aa8-11ea-89fa-8b736c61d86b.jpg)

**Comment by christophwaibel** [comment]
i love it. it is simple, yet aesthetic. very mermorable. let's use it!

this is a forum thread on how to add the icon to our hive tab:
https://discourse.mcneel.com/t/add-a-custom-icon-image-to-grasshopper-plugin-tabs/61777/19

**Comment by christophwaibel** [comment]
I'm hyped about it. I'll make a branch now for implementing the logo!

**Comment by christophwaibel** [comment]
yeah it works:
![image](https://user-images.githubusercontent.com/21927657/82452735-f3e44880-9aaf-11ea-9d2d-964533bdb60f.png)

@amraladdin could you modify the image to comply with the grasshopper icon format? I.e. 24x24 pixels png. Also, keep the background as transparent, then there won't be any white background anymore.

**Comment by amraladdin** [comment]
![hiveLogo_GH](https://user-images.githubusercontent.com/16256867/82455953-e29d3b00-9ab3-11ea-8f5a-d0c90b0ea263.png)

**Comment by daren-thomas** [comment]
@amraladdin can you please re-adjust the line widths? (save as .png 24x24)
@christophwaibel add to hive codebase

**Comment by amraladdin** [comment]
Hello @daren-thomas @christophwaibel Here's the latest version:
![hiveLogo_GH](https://user-images.githubusercontent.com/16256867/82911027-abbf9d00-9f6b-11ea-8b01-24cea605b702.png)

If you zoom in, it looks like this:
![image](https://user-images.githubusercontent.com/16256867/82911146-d3166a00-9f6b-11ea-9e79-a42145a3e282.png)

**Comment by amraladdin** [comment]
A couple of more alternatives... Not much difference though:

![hiveLogo_GH_02](https://user-images.githubusercontent.com/16256867/82913324-75375180-9f6e-11ea-9e7c-4f6d30f7ce1c.png)

![hiveLogo_GH_03](https://user-images.githubusercontent.com/16256867/82913327-75375180-9f6e-11ea-9a79-8cbcf1deefe4.png)

**Comment by christophwaibel** [comment]
ok cool I'll use the first one! 
fyi, if you want the white to be transparent, you have to save it properly. like this here:

![Hive_Icon](https://user-images.githubusercontent.com/21927657/82914656-1246ba00-9f70-11ea-9b5c-b5e1932ba6d3.png)
