### ISSUE TITLE
Analyze the results of the EuKSII survey

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/hive#253]
Analyze the results from the survey prepared for the EuKS II lecture.

**Comment by daren-thomas** [comment]
@amraladdin wants to add some more graphs based on @christophwaibel 's comments.

**Comment by amraladdin** [comment]
Could you use the graph visualization format for all questions? That would be easier to read than the questions where you did not use the graphs.
Also, could you make a scatter matrix with the answers? That way, we can correlate people who said they don’t know much rhino with responses that found the exercises too difficult.

===

![image](https://user-images.githubusercontent.com/16256867/81301674-a44a5980-9079-11ea-86eb-715ace351fd7.png)

**Comment by amraladdin** [comment]
![image](https://user-images.githubusercontent.com/16256867/82031691-8b096480-969a-11ea-9541-2519935ccb41.png)

![image](https://user-images.githubusercontent.com/16256867/82031765-9fe5f800-969a-11ea-9f5d-e81f28f84099.png)

![image](https://user-images.githubusercontent.com/16256867/82031783-a2485200-969a-11ea-8833-000443966b2c.png)

![image](https://user-images.githubusercontent.com/16256867/82031806-aa07f680-969a-11ea-96d4-fbd824fadf9b.png)


![image](https://user-images.githubusercontent.com/16256867/82031819-af654100-969a-11ea-8fb5-9b18c2c82392.png)

![image](https://user-images.githubusercontent.com/16256867/82031952-dc195880-969a-11ea-9054-a8fca4b87efb.png)
