### ISSUE TITLE
improve Icons for Hive.IO

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#254]
the only icon I find acceptable so far is the visualizer. However, it looks more like heart beat, and not like building simulation results.
environment icon has potential. 
but solar and building icons are very meh.

colors look like a tatoo. dislike.

![image](https://user-images.githubusercontent.com/21927657/80137954-5d059880-85a4-11ea-9b1d-426cc414e978.png)

**Comment by ChrisZenhub** [comment]
closing, as this has already been done by @lillaa
