### ISSUE TITLE
icons for Mothercell components

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#255]
![image](https://user-images.githubusercontent.com/21927657/80138404-106e8d00-85a5-11ea-8e03-cc3a42642573.png)

**Comment by ChrisZenhub** [comment]
self-assigned, coz i have a pen and wanna try pixel art

**Comment by amraladdin** [comment]
Shouldn't we close this issue? Now that we don't have a mothercell? :)

**Comment by christophwaibel** [comment]
no no, the "mothercell" components are also those that manage the inputs-outputs to and from the "Core" components.

Also, the cluster idea is not dead yet... :)

**Comment by ChrisZenhub** [comment]
https://developer.rhino3d.com/guides/grasshopper/grasshopper-icons/
