### ISSUE TITLE
Create / Assign the remaining icons for Core (the honey-badger created components)

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/hive#258]
#134 dealt with adding an icon functionality to honey-badger and then re-compiling the components in Hive.Core with these icons. I couldn't assign all icons as the naming scheme was not quite right and I don't think all components had an associated icon. They have been assigned a temporary "smiley" icon for the mean-time to make them easy to spot.

**Comment by daren-thomas** [comment]
The idea is to create (or locate) the correct icon and replace the corresponding .png file in the Core folders. They should be named the same as the python file computing the results - a simple and easy naming scheme.

**Comment by ChrisZenhub** [comment]
making beautiful icons is hell-of-a-work. changing time estimation.

see related issue #480 for Hive.IO icons

**Comment by ChrisZenhub** [comment]
how can we add an icon to a list component, @daren-thomas ? just add `"icon": ...` to here?

```
    {
      "class-name": "Sia2024RoomList_Ideal",
      "name": "SIA 2024 Ideal Rooms",
      "abbreviation": "Sia2024RoomsIdeal",
      "description": "A list of SIA 2024 rooms, ideal building quality",
      "category": "[hive]",
      "subcategory": "Demand",
      "id": "772400f7-ee9a-4e53-b33d-bf0d676f4249",
      "parameter-type": "ValueList",
      "csv": "..\\..\\Hive.IO\\Hive.IO\\Resources\\201008_SIA2024_Raumdaten_Zielwert.csv"
    }
```

**Comment by ChrisZenhub** [comment]
closing this issue as redundant and partly already completed by @lillaa
