### ISSUE TITLE
try Hive on Mac via Virtual Machine Windows 

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#262]
one student said, Hive didn't work with VM Fusion 10

**Comment by ChrisZenhub** [comment]
a student commented on this after the last lecture:

"Vielleicht die Benutzbarkeit auf Mac prüfen oder ev. für die Studienzeit einen Fernzugriff auf einen ETH PC über VPN ermöglichen. Arbeiten momentan so im Designstudio von Prof. Girot so über die LVML PCs welche auf Windows basieren."

**Comment by ChrisZenhub** [comment]
and another student wrote this:

"It would be great, if the script would run on mac too. Most of the students in the studios are using mac and often there are scripts nowadays for mac users too. Thanks!"

**Comment by ChrisZenhub** [comment]
@daren-thomas maybe you could have a look at this after #364?

**Comment by ChrisZenhub** [comment]
@lillaa tested, and it works
