### ISSUE TITLE
Send an update report to Innovedum

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/hive#265]
Send a 1-3 pager update on the status of the tool and the recent test run and survey.

**Comment by ChrisZenhub** [comment]
@amraladdin hit me up if you need help with this. I would enjoy writing actual sentences every now and then.

**Comment by ChrisZenhub** [comment]
we will have our LET interview mid-end October. So this issue is outdated, as we'll have to prepare for that interview instead
