### ISSUE TITLE
Roadmap to Hive v1.0

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#268]
update and make a Roadmap for HIVE v1.0
Hive v1.0 needs to be ready for deployment for Winter Semester 2020

RoadMap, drawn as Flowchart/Gantt Diagram, should contain packages categorized as:

- minimal viable product
- optional features
- ideal world features

**Comment by daren-thomas** [comment]
progress: new milestone (Hive 1.0)
