### ISSUE TITLE
improve HIVE.Core icons

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#269]
A great start! But let's make them more sexy!

![Unbenannt.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/fa83619d-7c3d-4b37-92da-53a4de3e31c2)

**Comment by ChrisZenhub** [comment]
Hive Core and Hive IO experienced a massive re-design. Putting this into icebox for now, until the used grasshopper components are more definite

**Comment by ChrisZenhub** [comment]
Demand:
- Häuser helleres Blau für stärkeren Kontrast

![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/4de0f1a0-2319-41e3-b348-db2c33c20c7c)

**Comment by ChrisZenhub** [comment]
EnergySystems

- etwas größeres "COP"

![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/d8b32462-f0f1-415e-b534-8d531a2d825a)

**Comment by ChrisZenhub** [comment]
IO-Core

Merger icons alle mit gestrichelten Pfeilen und weißen Rahmen

![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/4e6e106c-830e-418a-93a2-6b02dee66738)

**Comment by ChrisZenhub** [comment]
Solar

- Solar Thermal fehlt
- Photovoltaic (non-time resolved) gleich wie time resolved, aber ohne Uhr
- Summarize yield, PV wegnehmen
- Average yield, PV wegnehmen 

![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/57bd09bc-c32e-4983-8a43-b7a1c27fbfc3)

**Comment by lillaa** [comment]
Hi Chris

Die aktuellen Icons kannst du hier herunterladen:
[Hiveicons_200111.zip](https://github.com/architecture-building-systems/hive/files/5794959/Hiveicons_200111.zip)

Ich habe Paar Kommentare:

1. Bei IO Core ist mir die Benennung unlogisch geschienen (Position der Unterstrich), vielleicht hat es aber doch eine Logik, also ich habe trotzdem alles so benannt wie du hier aufgelistet hast:
_IO_CoreDistributor.png
IOCore_Distconvtech.png_

2. Ich denke, du hast _solar_ListPerformanceRatio.png_ und  _solar_PerformanceRatio.png_ aber umgetauscht. Ich habe die Liste als Liste benannt.

3. Gewisse alte Komponente fehlten komplett von deiner Auflistung. Vielleicht weil du sie nicht brauchst. Ich habe diese in einem separaten Ordner gespeichert, vielleicht brauchst du sie trotzdem. 
- Alle Input Komponente, Distributer Energy System, Distributer Energy Emitter, EPW etc.

Gib mir Bescheid, ob dunoch irgendetwas ändern würdest!

LG Lilla

**Comment by christophwaibel** [comment]
oh no, you're right. Somehow, I forgot all IO components. They were all fine though, apart of the wrong image size (must be 24x24 pixels)

![image](https://user-images.githubusercontent.com/21927657/104176945-49d37b00-5408-11eb-94e2-95a7d82d0887.png)

names, from top to bottom:

- ``IO_Building.png``
- ``IO_Energysytems.png``
- ``IO_Environment.png``
- ``IO_Results_Param.png``
- ``IO_Visualizer.png``
- ``IO_Para_Inputenergyemitter.png``
- ``IO_Para_Inputenvpot.png``
- ``IO_Para_Inputen.png``
- ``IO_Para_InputSIAroom.png``
- ``IO_Para_InputSolarTech.png``

**Comment by christophwaibel** [comment]
und bei Misc:

![image](https://user-images.githubusercontent.com/21927657/104177370-eeee5380-5408-11eb-9384-ddd7b1e30375.png)

- ``epw_reader.png``

**Comment by lillaa** [comment]
Ich habe diese in dem Ordner "PNG / +" gespeichert. Soll ich diese umbenennen und noch mal schicken?

**Comment by christophwaibel** [comment]
> Ich habe diese in dem Ordner "PNG / +" gespeichert. Soll ich diese umbenennen und noch mal schicken?

ja, bitte. Dann haben wir es für die Zukunft konsistent. Sorry 🙈

**Comment by lillaa** [comment]
Sicher! :) 
Hier: 
[Hiveicons_210111_2.zip](https://github.com/architecture-building-systems/hive/files/5795756/Hiveicons_210111_2.zip)
