### ISSUE TITLE
Compare computational performance of outputting struct versus List<GH_Number>

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#273]
writing timeseries (with 8760 entries) as List<GH_Number> outputs feels slow. Compare, if it is faster when outputting a `double [ ] data` (or whatever equivalent in python that would be) as GenericParameter.

So: `pManager.AddGenericParameter(..., GH_ParamAccess.item)` vs. `pManager.AddNumberParameter(..., GH_ParamAccess.list)`

**Comment by daren-thomas** [comment]
@christophwaibel would you mind explaining what the difference is? How does the `GH_ParamAccess` influence how the thing works? Asking, because I really don't know.

Also "feels slow" - are you sure? Have you measured this somehow?

**Comment by christophwaibel** [comment]
> @christophwaibel would you mind explaining what the difference is? How does the `GH_ParamAccess` influence how the thing works? Asking, because I really don't know.
> 
> Also "feels slow" - are you sure? Have you measured this somehow?

In Grasshopper, numeric data is implicitly converted into GH_Number data types if the output type is set to NumberParameter. GenericParameter on the other hand wraps the data into a GH_ObjectWrapper, I believe. 

Long Nguyen told us doing the conversion to GH_Number explicitly within the Solve( ) speeds it up by quite a bunch. So we could try that first. But still, we don't necessarily need to have all timeseries as GH_Numbers, so we should also check if keeping them as GenericParameters makes things faster.

"feels slow": from my experience. Crunching few ten thousand numbers shouldn't make my computer stutter, it should be instant. Measuring it would be part of this issue

**Comment by daren-thomas** [comment]
Thank you for the clarification. I think we should consider creating a TimeseriesParameter for this kind of stuff, what do you think?

**Comment by christophwaibel** [comment]
good idea, let's do it!

**Comment by ChrisZenhub** [comment]
data types in grasshopper: https://developer.rhino3d.com/guides/grasshopper/grasshopper-data-types/

**Comment by christophwaibel** [comment]
wow check this out @daren-thomas . `GH_Numbers` are VERY slow.
that's enough proof for me to use custom params wherever we have more than ~10000 numbers...

![image](https://user-images.githubusercontent.com/21927657/84903707-b96dcb80-b0ae-11ea-8510-4fec36dbc047.png)

![image](https://user-images.githubusercontent.com/21927657/84903448-698f0480-b0ae-11ea-8738-f9124b78716b.png)

![image](https://user-images.githubusercontent.com/21927657/84903426-6136c980-b0ae-11ea-8ca1-5539a53d5f55.png)

![image](https://user-images.githubusercontent.com/21927657/84903490-77448a00-b0ae-11ea-80e9-aa29aacbf6f8.png)

![image](https://user-images.githubusercontent.com/21927657/84903537-83c8e280-b0ae-11ea-871a-98f6cbb173c9.png)

**Comment by christophwaibel** [comment]
description: 
- the `CustomClass` component reads in and writes out a custom class (sorry, it says struct on the component, but thats just a wrong wording)
- whereas the `GH_Numbers` reads in and writes out a list of GH_Numbers
- the length of the arrays/list is the number in the yellow box
- the arrays/lists really are just `for(int i=0; i<horizon; i++) { array[i] = i; }`, respectively `for(int i=0; i<horizon; i++) { list.add = i; }`

**Comment by christophwaibel** [comment]
...and some more insights on explicit conversion. makes it a bit faster, but CustomClasses are still way faster. Not sure though, if I can also explicitly convert to `GH_List`, instead of `List<GH_Number>`...

![image](https://user-images.githubusercontent.com/21927657/84908918-5d5a7580-b0b5-11ea-849d-de9757b89bdc.png)

```
        protected override void SolveInstance(IGH_DataAccess DA)
        {
            int horizon = 0;
            DA.GetData(1, ref horizon);

            var numbersIn = new List<double>();
            DA.GetDataList(0, numbersIn);

            var numbersOut = new List<GH_Number>();
            for (int i = 0; i < horizon; i++)
                numbersOut.Add(new GH_Number((double)i));
            DA.SetDataList(0, numbersOut);
        }
```

**Comment by christophwaibel** [comment]
> ...Not sure though, if I can also explicitly convert to `GH_List`, instead of `List<GH_Number>`...

ok, i don't think so. SetDataList implement IEnumerable
https://developer.rhino3d.com/api/grasshopper/html/M_Grasshopper_Kernel_IGH_DataAccess_SetDataList.htm

**Comment by daren-thomas** [comment]
woah. now _that's_ what i'm talking about: measured performance. gopf. why oh why is the obvious way slow? but yeah. maybe thinking of a Timeseries as it's own "object" _is_ the smart way to do it...

**Comment by ChrisZenhub** [comment]
@daren-thomas so for the dataflow from Inputs into the core, within the core, as well as from core to outputs, I will use custom classes (e.g. `Results.cs`, `Building.cs`, etc) for now.

The Visualizer component, however, could maybe output and read a custom `GH_Param<HiveResults>`, which could be used also to store results into that grasshopper param. Let's put this as lower priority for now (maybe after the MVP release, or if we have time in the last 2.5 weeks before mid September) #270 #212 #184
