### ISSUE TITLE
Use hourly solar simu for monthly SIA demand for active shading exercise

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#276]
- for active shading, we need hourly resolution
- but our Hive SIA demand calculations are monthly

possible solutions:
- A) we run sia demand calculations hourly. that requires us to have schedules etc
- B) since it is about active shading, we could simply say "cap solar insolation on windows at 200W/m2" (solar simulation is hourly already in Hive)

**Comment by ChrisZenhub** [comment]
going for b)

**Comment by ChrisZenhub** [comment]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/ebeea9ef-0443-4ce1-aa27-e21aa1ec6884)

https://app.zenhub.com/workspaces/eacsiii-hs20-5eb9670fc0c36b46948cd1aa/issues/architecture-building-systems/eacsiii/80

**Comment by ChrisZenhub** [comment]
resolved via #451
