### ISSUE TITLE
Add surface type string output to Building Distributor

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#281]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/01387df2-82f8-40f2-804b-5902e3cd784b)

output list of strings that describe surface type. needed for honey-badger sia380 component.

currently only implemented as custom ghpython component

**Comment by ChrisZenhub** [comment]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/01387df2-82f8-40f2-804b-5902e3cd784b)

not sure about the above comments, but let's do this here for sure: output list of strings that describe surface type. needed for honey-badger sia380 component

**Comment by ChrisZenhub** [comment]
i have no idea anymore, what this issue is about...
