### ISSUE TITLE
sia380 make 3 levels of irradiation calculation

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#282]
for the new sia380.py component:

make 3 levels of obstruction calculations:
- level 1: no obstruction, when no obstacle meshes are provideed
- level 2: simple one-way ray-mesh intersection with coarse skydome, if obstacle mesh provided. Compute viewfactor and use it as reduction factor for unobstructed solar irradiation calculation with SoladModel.dll
- level 3: full SolarModel.dll and GHSolar.gha, if "advanced obstruction calc" (or similar) is set to true

**Comment by ChrisZenhub** [comment]
at least 1 and 2 should be implemented. I.e. by default simple solar simu, but if users says "no obstructions", then no obstructions calculations are executed.

Using obstacles as switch is not robust, because the building could cast shadow on itself.
