### ISSUE TITLE
Using hive for the Integrated Design MBS course (HS20)

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/hive#283]
Can we use hive for simplified demand and supply simulations for IDP HS20?
- Running quick demand and supply simulations for MFH. Goal is to have a Carbon Neutral housing project.
- Can we use the Shoebox method to compensate for the missing multi-thermal zone model?

**Comment by daren-thomas** [comment]
we decide hive is not the best solution for the IDP HS20
