### ISSUE TITLE
3d-visualization of losses and gains

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#287]
displaying them as coloured arrows in / out and coloured surfaces in Rhino viewport. Numbers from SIA380 component (Q_T, Q_V, Q_i, Q_s)

**Comment by ChrisZenhub** [comment]
protoype: ![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/327bc1dc-23f7-43a9-bd2a-c1408600149e)

**Comment by philipschulz** [comment]
closing as redundant
