### ISSUE TITLE
Data for simplified LCA

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#291]
Simplified LCA of construction and energy technologies.

We already identify individual building surfaces (roof, floor, wall. Windows and solar tech surfaces). So we can use that, together with information on the respective construction type or solar technology, and compute simplified LCA.

Additionally, we have to compute embodied emissions of energy technologies (heat pump, boiler, etc.). We have a separate issue for operational carbon emissions of these technologies.

**Comment by ChrisZenhub** [comment]
@hillias has looked into SIA Effizienzpfad Energie which has info on construction LCA.

Illias raises the issue of Mobility, which is a significant part of total emissions.

http://www.library.ethz.ch/Ressourcen/Datenbanken/eresearchcenter

**Comment by amraladdin** [comment]
Could this be of help? It's a document we prepared for the IDP course in 2018.

[KBOB_LCA_data_in_the_building_sector_EN.xlsx](https://github.com/architecture-building-systems/hive/files/4734889/KBOB_LCA_data_in_the_building_sector_EN.xlsx)

**Comment by christophwaibel** [comment]
missing entirely so far in #363. see mail to @Linwal on 19.8.'20

**Comment by christophwaibel** [comment]
hey  @Linwal , for now please add data into these files:

https://github.com/architecture-building-systems/hive/blob/master/src/Hive.Core/sia380/200728_SIA2024_Raumdaten_Bestand.csv

https://github.com/architecture-building-systems/hive/blob/master/src/Hive.Core/sia380/200728_SIA2024_Raumdaten_Standardwert.csv

https://github.com/architecture-building-systems/hive/blob/master/src/Hive.Core/sia380/200728_SIA2024_Raumdaten_Zielwert.csv

**Comment by Linwal** [comment]
@christophwaibel 
I will add some basic cost data for walls but does it make sense to couple these with the SIA buildin category? Could be something to think about after the beta release.

**Comment by christophwaibel** [comment]
yes, you're right. We would have to somehow indicate it that cost and emission data is not from SIA. Probably somewhere on the windows form (the GUI thing on grasshopper).

Data-wise, it is convenient to have it in the same file though

**Comment by Linwal** [comment]
ok, done for the walls. However for the data I found it was not possible to make different prices for different SIA categories. (Which anyway does not make too much sense.) For now it is a standard concrete construction with mineral wool insulation for all types. And a wooden frame window.
I added a docx file with the sources to the numbers.
