### ISSUE TITLE
Input GH component for Manual design of composition of multi-energy system

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#292]
Make an Hive Input Energy Systems component, where the user (via a form) can specific the composition and capacity sizing of a multi-energy-system, following Martin’s approach.
its called system chain diagram. related issue #315

**Comment by amraladdin** [comment]
Not sure if this is related, but this document contains simplified energy systems calculations

[Simplified_District_energy_Assessment.xlsx](https://github.com/architecture-building-systems/hive/files/4734926/Simplified_District_energy_Assessment.xlsx)

**Comment by ChrisZenhub** [comment]
development:
- form coding @daren-thomas (Hive.IO.GHComponents.GHEnergySystem.cs; doesn't exist yet)
- UI design @amraladdin 
- data flow into the Core @christophwaibel (Hive.IO.EnergySystems)

**Comment by ChrisZenhub** [comment]
#142 solar tech input form will be integrated into an Energy Systems input form

**Comment by ChrisZenhub** [comment]
duplicate #343
