### ISSUE TITLE
Account for Solar thermal energy in Results

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#296]
In Hive Core, make sure that solar thermal and PVT’s heat energy generation is accounted for properly in the monthly energy demand charts. Currently, only PV is considered in the monthly electricity demand charts.

**Comment by amraladdin** [comment]
Found this document from the MBS course in HS18. Might be helpful.

[20170924_MBS_Supply.pdf](https://github.com/architecture-building-systems/hive/files/4734916/20170924_MBS_Supply.pdf)

**Comment by ChrisZenhub** [comment]
I think it is... anyway redundant issue with #337
