### ISSUE TITLE
Simplified costs calculation Energy Systems

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/hive#301]
I found this document while checking some sheets we prepared for the MBS HS18. I believe it might be helpful for the cost estimates. They're extracted from the CEA as well.
[https://app.zenhub.com/files/110542628/c343e8d7-fc57-448a-b251-603c9d6883ca/download](https://app.zenhub.com/files/110542628/c343e8d7-fc57-448a-b251-603c9d6883ca/download)

**Comment by christophwaibel** [comment]
this is great! 👍 

The readme-tab is a little short though. I assume the IC equation has been formulated to fit different curves? I would find it helpful for the credibility of this dataset to state sources for the individual technologies.

**Comment by ChrisZenhub** [comment]
using just linear cost for the MVP: c = ax
