### ISSUE TITLE
Add a property TotalFloorArea to the Hive.IO.Result object

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/hive#303]
The GHVisualizer needs to know the area to be able to produce the normalized plot. I can't figure out how to get this information.

For the moment, on my branch (`209-heating-cooling-dhw-monthly`) I'm adding a dummy property to `TotalFloorArea` that is set to 100.0 in the constructor.

**Comment by ChrisZenhub** [comment]
TotalFloorArea also needs to be processed within the core, specifically, it needs to be read by the GHResults component
