### ISSUE TITLE
Barplot with monthly operational and embodied emissions of energy systems

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#304]
Create stacked values, similar to the below bar charts for Monthly operational and embodied carbon emissions.

@christophwaibel sends monthly values example of operational and embodied carbon to Amr.
Then Amr creates the graphs description for Daren.
Then Daren implements.

Operational carbon
![image](https://user-images.githubusercontent.com/16256867/84279145-e9a8ed80-ab35-11ea-9d3b-16bed31de04b.png)

Embodied Carbon

**Comment by amraladdin** [comment]
Update: This issue connects to issues #305 #306 #307 and #308

**Comment by amraladdin** [comment]
Look at this sweet plot:
![image](https://user-images.githubusercontent.com/16256867/86484678-1035ff00-bd57-11ea-81e8-79ad70d31831.png)

**Comment by daren-thomas** [comment]
implemented as of pr #336
