### ISSUE TITLE
change arrows in GHVisualizer to drop down and add button for yearly to monthly

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#309]
instead of the left right arrows, let us make a drop down, where the user can select the plot he wants to see.

**Comment by amraladdin** [comment]
@daren-thomas what information do you need from me for this issue?

**Comment by amraladdin** [comment]
@daren-thomas @christophwaibel See the attached PDF for detailed instructions:
[KPI_Visualizer_Buttons.pdf](https://github.com/architecture-building-systems/hive/files/4865284/KPI_Visualizer_Buttons.pdf)

**Comment by amraladdin** [comment]
![image](https://user-images.githubusercontent.com/16256867/86534464-f290a300-bed8-11ea-843f-eb888c19a674.png)

**Comment by daren-thomas** [comment]
Implemented in PR #336
