### ISSUE TITLE
team role discussion for until release Hive 1.0

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#320]
Hi guys,
in an effort to make sure we finish Hive 1.0 by September, I would like to discuss our Team Roles at the next sprint. This is my proposal:

![teamroles.PNG](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/65eb69b7-68e2-46eb-8b7f-39f2260fdf84)

[https://app.zenhub.com/files/110542628/5356aea8-d436-465e-87d0-9e97f673c785/download](https://app.zenhub.com/files/110542628/5356aea8-d436-465e-87d0-9e97f673c785/download)

**Comment by amraladdin** [comment]
:D Sounds great. Let's do that!

**Comment by daren-thomas** [comment]
I'm in!

**Comment by christophwaibel** [comment]
Task force Hive 1.0 :) 
@amraladdin @daren-thomas @hillias @Linwal 

![image](https://user-images.githubusercontent.com/21927657/85033947-cefff580-b181-11ea-8e91-e18dc9a76759.png)
