### ISSUE TITLE
Discuss w/ team regarding using the Barlow font

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/hive#321]
How about we use one font for the results. I really like this one, which is open source.
https://github.com/jpt/barlow
https://fonts.google.com/specimen/Barlow#about
Here is the zipped file of the font:
[Barlow.zip](https://github.com/architecture-building-systems/hive/files/4793367/Barlow.zip)

**Comment by ChrisZenhub** [comment]
@amraladdin i'm happy with whatever you decide. This font also looks nice. 

One thing to consider maybe: If this font needs to be installed separately by all potential Hive users, I would probably not use it and rather go for a standard font. I would prefer it, if everything Hive users have to install is a folder into their Rhino Grasshopper libraries folder. 

I don't know, how this is with fonts. You could discuss with @daren-thomas ?

**Comment by amraladdin** [comment]
I bet it can be part of the hive installer, no? If it's too difficult, then I can find a default one. I thought it's sexier for the users if the tool has its own character, including a different (architecty) font :)

**Comment by daren-thomas** [comment]
I bet this is something to tackle in a later stage... though I like the idea, it's probably not the first thing we should optimize.

**Comment by amraladdin** [comment]
Great. I'll move this issue to enhancement then and remove the milestone.
