### ISSUE TITLE
Data for PV, ST, PVT

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#322]
acquire and compile data for Photovoltaic, Solar Thermal, and hybrid PVT technologies:

- name of technologies
- embodied emissions
- investment cost (per m²)
- lifetime
- efficiencies
- operation cost?
- any other data, that is relevant for HIVE

**Comment by christophwaibel** [comment]
data in `PV`  and `Solar thermal` subfolders (#363) look good. I'll take them like that for the September release.

Note, that I've implemented ambient air temperature dependant efficiency equations for solar thermal and PV as well, but we can go for the constant efficiencies for now.

time-resolved functions here: https://github.com/architecture-building-systems/hive/blob/master/src/Hive.IO/Hive.IO/EnergySystems/SurfaceBasedTech.cs

![image](https://user-images.githubusercontent.com/21927657/90693627-74654180-e277-11ea-815f-358a58b3f4b3.png)

![image](https://user-images.githubusercontent.com/21927657/90693639-7af3b900-e277-11ea-8bcf-41a87061aeef.png)

**Comment by Linwal** [comment]
- Performance ratio is done
- PV efficiencies is updated with embodied emissions and basic cost data @christophwaibel The cost and emissions are given per kWp not per m2, is this ok?

Further, the choice was limited to only the favourable values for each technology. I talked about this with @hillias.

Please let me know if you need more

**Comment by christophwaibel** [comment]
Hi @Linwal , thanks for this! to which branch did you push your changes?

**Comment by Linwal** [comment]
@christophwaibel: I pushed it to lca_data

**Comment by Linwal** [comment]
Some data for solar thermal and PVT has been added. See the source.docx for sources. For PVT however the data is very generic
