### ISSUE TITLE
Coding Windows Form for Building Input

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#328]
coding this guy here: #126

**Comment by ChrisZenhub** [comment]
UI /UX design spec in #126

**Comment by daren-thomas** [comment]
@christophwaibel quick question: what gh file would be the best to work on this?

**Comment by daren-thomas** [comment]
ok. found a suitable one really easily: well done with the naming! good names help a lot!

also, it seems we can use WPF, so... I think we can actually make it look more or less _exactly_ like amr's design :-D
