### ISSUE TITLE
Severe bug in Visualizer

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#330]
Just discovered a rather severe bug with the Visualizer component, which makes a `.gh` file unopenable.

How to reproduce the bug:

- open `Hive_Results_Visualizer_Test.gh`
- select everything, right click, `Disable`:
![image](https://user-images.githubusercontent.com/21927657/86517660-e948fd00-be2a-11ea-921f-8856b4385b57.png)

- save the file
- close rhino
- open rhino, open grasshopper, try to open the `.gh` file. You'll get a bunch of error messages and a red grasshopper canvas with no content: 
![image](https://user-images.githubusercontent.com/21927657/86517681-21e8d680-be2b-11ea-9149-b4a52efd5318.png)

**Comment by ChrisZenhub** [comment]
seems to be fixed with #336
