### ISSUE TITLE
Finish the visualization masterplan and visualizer UI description

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/hive#331]
Finish a PPT presentation that shows a step-by-step walk-through how the visualizer will be used. This way @daren-thomas can work on the visualizer coding afterwards.

**Comment by amraladdin** [comment]
Hello @daren-thomas 👍 
Find below the final full version of the UI and UX of the visualizaer in this 87 slide document.
Let me know if you have any questions.

[200702_hive_Visualizer_Detailed.pdf](https://github.com/architecture-building-systems/hive/files/4885521/200702_hive_Visualizer_Detailed.pdf)

**Comment by ChrisZenhub** [comment]
well done, super cool plots. closing this now
