### ISSUE TITLE
feed real data into ResultsPlotter for AmrPlot

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#337]
...and maybe rename it to `ResultsAdaptor`

**Comment by christophwaibel** [comment]
https://github.com/architecture-building-systems/hive/issues/199#issuecomment-666289406

https://github.com/architecture-building-systems/hive/issues/215#issuecomment-666290346

https://github.com/architecture-building-systems/hive/issues/307#issuecomment-666291457

https://github.com/architecture-building-systems/hive/issues/306#issuecomment-666291961

https://github.com/architecture-building-systems/hive/issues/314#issuecomment-666293773

https://github.com/architecture-building-systems/hive/issues/317#issuecomment-666297014

**Comment by ChrisZenhub** [comment]
@christophwaibel first, make a list of what is still missing.
- [ ] Amr Plot Energy:
- [ ] Amr Plot Emissions:
- [ ] Amr Plot Costs:
- [ ] Sankey Diagram
- [ ] Monthly loads barplot
- [ ] monthly individual windows irradiation

**Comment by ChrisZenhub** [comment]
for E02, we actually have everything already

**Comment by ChrisZenhub** [comment]
@amraladdin let's talk ~1h and you can explain me the details of Amr Plot

**Comment by ChrisZenhub** [comment]
moving this to next sprint, because @amraladdin is on holiday

**Comment by amraladdin** [comment]
We can have a call tomorrow if you are free? I'm quite flexible.

**Comment by ChrisZenhub** [comment]
amr plot workshop doc: https://docs.google.com/presentation/d/1FJ1ZZXHWV4lAlZivqtyNx2I8tnIDKTHHKmVih2kN1ME/edit#slide=id.gb146780c39_0_376
