### ISSUE TITLE
Check SIA 2028 Solar Irradiation Model and incorporate Zurich climate at least

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/hive#35]
- [x] Extract Zurich climate data from SIA Norm 2028
- [ ] Give data to Saso
- [ ] Incorporate solar irradiation data in hive

**Comment by hillias** [comment]
![SIA2028extract.png](https://images.zenhubusercontent.com/5d1dfb57f9953d5554536994/a8eea8de-5f19-426e-a179-fca25922490c)

**Comment by daren-thomas** [comment]
This task will involve extending honey-badger to understand data files (I'd like to keep the input data as assembly resources or modules that can be imported).

**Comment by daren-thomas** [comment]
waitaminute:

- `Gh` is in `[kWh/m2]`, but our SIA 380.1 component expects an `I` in `[Wh/m2]` - are these supposed to be the same value? @hillias can you add some information here?

**Comment by christophwaibel** [comment]
I'll be creating a first sia 2028 component next

**Comment by christophwaibel** [comment]
> waitaminute:
> 
> * `Gh` is in `[kWh/m2]`, but our SIA 380.1 component expects an `I` in `[Wh/m2]` - are these supposed to be the same value? @hillias can you add some information here?

@daren-thomas sia2028 also provides I in Wh/m2, so I'll be outputting that
