### ISSUE TITLE
Expected <type> got <type> bug

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#356]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/2aa824c6-a649-419d-8bed-f7ba9378efad)

happens if an external, by Hive.Core referenced `.gha` library (e.g. `GHSolar.gha`) exists multiple times on the PC (e.g. in `\bin` and `\libraries`)

**Comment by daren-thomas** [comment]
is it really a bug? I think the problem might be, that you have the `\bin` folder added in the grasshopper developer settings?

**Comment by ChrisZenhub** [comment]
nope. it's a bug, somehow related to us mixing up honey-badger projects with .net projects. Also, the live-debugger in visual studio won't work as soon as there are honey-badger components involved

**Comment by daren-thomas** [comment]
can you provide an example `Libraries` folder and `.gh` file please?
