### ISSUE TITLE
Refine the full_workflow gha example file

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#366]
the typical simulation case should be working for the MVP
- design a building volume with windows and PV surfaces
- input all into Hive.Input components
- make your edits in the Input components (weatherfile, construction, setpoints, energy systems selection...)
- Hive.Core should run
- infuse all Hive objects with Hive.Core simulation results (Building, EnergyCarriers, etc)
- GhResultsVisualizer should show plots with real data

**Comment by christophwaibel** [comment]
`Hive_Full_Workflow.gh` as well as `Hive_Hidden_Core.gh` in `\GrasshopperExamples`
