### ISSUE TITLE
GhBuilding form doesn't accept list item with Sia rooms anymore

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#375]
![image](https://user-images.githubusercontent.com/21927657/91314046-6737dd80-e7b6-11ea-8fc4-1c652756caa8.png)

"Der angegebene Schlüssel wurde nicht gefunden".

`GhParametricInputSiaRoom` does work.

Use `Hive_Parametric_Inputs.gh` as example.

Not too important now, we don't really need the list-item currently, since the form is working

**Comment by christophwaibel** [comment]
see related #376

**Comment by ChrisZenhub** [comment]
closing as not a bug

`GhBuilding` component shouldn't read this list anymore, the user is supposed to use the form for it. The only input could be from the ParametricBuilding component
