### ISSUE TITLE
Amr Plot what exactly do the quadrants show?

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#381]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/9fff1365-9231-4384-9dc4-54c2caccd80c)

...updated note: instead of primary energy, we could plot consumed source carriers in the bottom right plot?

**Comment by ChrisZenhub** [comment]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/898fd2fd-508e-4b24-9f14-533d0e123164)

also here, what is operation energy building vs operation energy systems? Needs to be specified, what **exactly** is plotted where.

Also, in my opinion, these bar plot don't make much sense as long as we don't distinguish between demand type (heating, cooling, dhw, electricity) on the top plot, and carrier type (grid electricity, fuels, district heating...) on the bottom plot

**Comment by ChrisZenhub** [comment]
Also, why do we have tabs "Energy" and "Emissions", but then we also have 4 quadrants, "Embodied Building", "Embodied Systems", "Operation Building", "Opeation Systems"?

What do "Embodied" and "Emissions" mean?

**Comment by ChrisZenhub** [comment]
also, "Costs" tab doesn't fully work with 4 quadrants:
- operational cost of energy systems, bottom right quadrant, ok
- investment cost, bottom left quadrant, ok, but not time resolved
- operational cost of building, top right, how is this different to operational cost of energy system?
- investment cost of building, top left, ok, but not time resolved

@amraladdin I think we need some re-design / specifications after the next weeks release :)

**Comment by ChrisZenhub** [comment]
make sure non-time-series-data is also shown as non-time-series data

![image](https://user-images.githubusercontent.com/62353294/101787334-43976980-3aff-11eb-9baf-74c8e7f3a085.png)

**Comment by amraladdin** [comment]
This issue is done, no?

**Comment by ChrisZenhub** [comment]
yup, notes of our workshop here:
https://docs.google.com/presentation/d/1FJ1ZZXHWV4lAlZivqtyNx2I8tnIDKTHHKmVih2kN1ME/edit?usp=sharing

I'll make separate new issues for the to-do's
