### ISSUE TITLE
energy systems form some data not shown 

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#385]
![image](https://user-images.githubusercontent.com/21927657/92486168-11b6f400-f1ec-11ea-8687-c09199fcdb82.png)

From the json:  
```
{
      "Name": "Monocristalline (23%)",
      "ElectricEfficiency": 0.228,
      "ThermalEfficiency": 0.00,
      "SpecificCapitalCost": 3076,
      "SpecificEmbodiedEmissions": 833
    },
```

Only efficiency and name are shown on the form.

m2 is missing on the form. 

btw, in the json, specific capital cost are CHF / kWp, and Specific embodied emissions are kgCO2 / kWp

cost per m2 can be calculated by SpecCapitalCost * ElectricEfficiency; embodied emissions per m2 can be calculated by SpecEmbodiedEmissions * ElectricEfficiency

Same for Solar thermal, just replace elecitrc efficiency with thermal efficiency

**Comment by daren-thomas** [comment]
@christophwaibel where on the screen to put the area? i'm guessing _at least_ the correct calculations need to go into the mvp?

**Comment by daren-thomas** [comment]
(I can hide the "technology image" for now?)

**Comment by daren-thomas** [comment]
_OR_ place it below the selection of surfaces. actually, that would work nicely!

**Comment by christophwaibel** [comment]
@daren-thomas actually, keep the calculation of CAPEX and embodied emission as it is. I will use values per m2, and not per kWp

**Comment by daren-thomas** [comment]
huh. just implemented it the other way round... wait. i'll create a pull request and you can decide. ALSO, do we show _specific_ capex and emissions or multiply by area?

**Comment by christophwaibel** [comment]
hold on, you're right. @daren-thomas 
we wanna have specific cost and emissions as a variable for the user to change

total cost and emissions should still be displayed somewhere, but not as a dependant variable (user shouldnt be able to change it)
