### ISSUE TITLE
Re-design building hizard- see which parameters change based on room type

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#386]
![image](https://user-images.githubusercontent.com/21927657/92489532-2a290d80-f1f0-11ea-8683-9eeb6ab84ba5.png)

If you wanna check which values change based on the sia room type, it is a bit tedious to jump between tabs. maybe change to sth like this?

**Comment by daren-thomas** [comment]
hmm... we _could_ - but that will make the "Env" tab a bit difficult to squish into the (already) tall height.

maybe @amraladdin can come up with an improved design? I suggest we do this after the mvp?

**Comment by christophwaibel** [comment]
@daren-thomas not for the mvp :) just for something to discuss afterwards

**Comment by ChrisZenhub** [comment]
@christophwaibel specifiy design changes

**Comment by christophwaibel** [comment]
![image](https://user-images.githubusercontent.com/21927657/144860455-abe9fd8f-78ee-4c77-b0ad-0808f72eb9ac.png)

![image](https://user-images.githubusercontent.com/21927657/144860479-64835be4-e476-4539-831b-efb0d2e986f9.png)

![image](https://user-images.githubusercontent.com/21927657/144860503-bbe2ffcc-21d7-46e5-88f7-526e9123f8c4.png)

![image](https://user-images.githubusercontent.com/21927657/144860524-9868a51c-6aba-4e2c-8177-2ba2eaa1d76f.png)

@philipschulz let me know if anything should be unclear
