### ISSUE TITLE
Add active cooling arrow to building energy sankey

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#388]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/71027b41-62e5-4784-b7a5-cb4fbd29f6f9)

Can we add this, @daren-thomas ?

**Comment by daren-thomas** [comment]
of course we can! @christophwaibel priority?

**Comment by christophwaibel** [comment]
@daren-thomas priority, hm.. not really. I can just show examples without cooling loads :D

**Comment by daren-thomas** [comment]
@amraladdin what color?

**Comment by ChrisZenhub** [comment]
hi @daren-thomas :

could you do following changes to the sankey diagram:

- add arrow in "Outputs" for "Surplus Electricity" - color: #CCFF99, RGB 204,255,153
- add arrow in "Outputs" for "Active Cooling" - color: #CCFFFF, RGB 204,255,255
- deactivate the arrow in Outputs "Primary Transfer Losses" for now, because I don't know what to plug in here

Colors can be improved later by our Designer
