### ISSUE TITLE
show kWh in building energy sankey and compute arrow sizes differently

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#389]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/46bef88d-e922-4091-8e47-c6ca9bec7aa7)

can we add an option to display kWh, instead of %?

Also, you compute 100% for the left and right arrows separately. But what if there is surplus input energy (overheating)? would be good to see that in the diagram. Can you therefore compute 100% based on the largets energy stream (either input or output)? E.g. energy in is 1000kWh and output energy is only 500 kWh, then 1000 kWh is assumed to be 1000% and in the diagram it will be possible to recognize that energy out arrows are not big enough. Vice versa, if energy out is larger, then that is assumed to be 100%

@daren-thomas

**Comment by daren-thomas** [comment]
@christophwaibel sure. totally possible. what is the priority?

**Comment by christophwaibel** [comment]
@daren-thomas also no priority right now. Again, I can only show examples where input = output

**Comment by daren-thomas** [comment]
actually: kWh AND % (e.g. "1756 kWh (20%)")

**Comment by daren-thomas** [comment]
![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/8f5d00a1-60f4-4c04-9cca-13e1f3534e7b)
