### ISSUE TITLE
Add PEF parameter to Grid Electricity energy carrier

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#390]
should be an optional parameter? Boolean to indicate grid electricity? If `Electricity` is created from PV or CHP, PEF could be calculated based on the fuel of CHP, and for PV, PEF would be 0

implement as part of electricity grid conversion technology? #382

**Comment by christophwaibel** [comment]
Swiss grid: 40% nuclear, 60% hydro (sauce: Marc)

PEF nuclear: 2.8
PEF hydro: 0.5
sauce: http://go.leonardo-energy.org/rs/europeancopper/images/PEF-finalreport.pdf , table 2-1
