### ISSUE TITLE
energy systems form has wrong parameter names

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#391]
The form, as well as the json has some wrong parameters (https://github.com/architecture-building-systems/hive/edit/master/src/Hive.IO/Hive.IO/EnergySystems/conversion_technology_defaults.json)

- heat to power ratio is only for CHP and not for any other conversion tech. 
- Heat/Cooling Exchanger doesnt have an efficiency parameter, but distribution losses.
- ASHP and Chiller have Efficiency (COP is calculated based on source and sink temperatures, so we don't display it on the form yet)

could you please match with `ConversionTechProperties` in https://github.com/architecture-building-systems/hive/blob/master/src/Hive.IO/Hive.IO/GhParametricInputs/GhConversionTech.cs ?

@daren-thomas

**Comment by daren-thomas** [comment]
see PR #392 for implementation
