### ISSUE TITLE
Add default input values to the SIA 380 component

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/hive#40]
- [x] Assign this issue to Saso Basic
- [ ] take the list of inputs and their default values from Illias (per building use type).
- [ ] Edit the SIA component to host the chosen default values.

**Comment by daren-thomas** [comment]
BTW: the newest version of honey-badger now supports a `default` key for input dictionaries. See the `examples/helloworld/helloworld.json` badger-file for an example.

**Comment by Bombyx-ETH** [comment]
Isn't there supposed to be a PDF with default values attached to this issue?
