### ISSUE TITLE
COP equation in equation sheet wrong temperatures

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#402]
![image](https://user-images.githubusercontent.com/21927657/93005130-588b4d80-f54e-11ea-8470-d4e9ea0a3f47.png)

Shouldn't this be evaporator and condensor temperatures, instead of supply and source temp @hillias ?

**Comment by christophwaibel** [comment]
https://industrialheatpumps.nl/en/how_it_works/cop_heat_pump/

**Comment by hillias** [comment]
I agree supply and source temp are confusing terms. However, I doubt that many students will know the meaning of evaporator and condenser temperature. How about we just call it T_hot and T_cold instead (https://en.wikipedia.org/wiki/Heat_pump). This is easy to understand and scientifically correct. I would also adjust those terms in the formula sheet.

**Comment by christophwaibel** [comment]
yes you're right, ok!

**Comment by christophwaibel** [comment]
but it'll be two COP eqtuations, one for heating, one for cooling

**Comment by christophwaibel** [comment]
closing this issue, as it doesn't affect Hive and I want to reduce the pile of issues ;-)
