### ISSUE TITLE
call SolveInstance only if state_before != state_now

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#405]
when closing the forms (Building and EnergySystems), the grasshopper canvas is re-computed because `SolveInstance( )` is called in these forms. But if the user doesn't change anything in the form, the new state is identical to the previous state, so it wouldn't be necessary to recompute the canvas.

Can we make it such that it only calls SolveInstance if the state of the form changed?

**Comment by ChrisZenhub** [comment]
closing as redundant with #603
