### ISSUE TITLE
Create a set of use cases and define their default input values to add to the SIA 380 component in GH

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/hive#41]
- [ ] create a list of default input values in Excel. Define these values for 4 use types:
a) SF residential, b) MF residential, c) Office, d) School.

**Comment by hillias** [comment]
Hi Daren

Please create a new component 'SIA 2024 - use case data' as follows:

Inputs:
Use case (Default value: Single family home)
A - Living area [m2]
month [-]

Outputs:
U_op - U value opaque walls [W/(m2K)]
U_w - U value windows [W/(m2K)]
tau - time constant [h]
Ve - Exterior air volume flow rate per square meter of living area [m3/h]
Vinf - Infiltration air volume flow rate per square meter of living area [m3/h]
eta_rec,theta - ventilation heat recovery efficiency [-]
Phi_Peop - Heat release People [W]
Phi_Light - Heat release Lightning [W]
Phi_Appl - Heat release Appliances [W]
t_Peop - full load hours People [h]
t_Light - full load hours Lightning [h]
t_Appl - full load hours Appliances [h]
g - g-Value windows [-]

Component:
Based on input 'use case', look up U_op; U_w; tau; q_v,e; q_v,inf; eta_rec,theta; Phi_P; Phi_A; Phi_L; t_P; t_A; t_L; g  (all standard values) from table (see attachment)
[SIA 2024_2015_SFH_MFH_OFFICE_SCHOOL.pdf](https://github.com/architecture-building-systems/hive/files/3362752/SIA.2024_2015_SFH_MFH_OFFICE_SCHOOL.pdf)
.

Calculate:
Ve = A * q_v,e
Vinf = A * q_v,inf
Phi_Peop = A * Phi_P
Phi_Light = A * Phi_L
Phi_Appl= A * Phi_A 
t_Peop = 30 * t_P #assumes every month has 30.5 days, simplification
t_Light = 30 * t_L #assumes every month has 30.5 days, simplification
t_Appl = 30 * t_A #assumes every month has 30.5 days, simplification
