### ISSUE TITLE
make a documentation framework

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#413]
Including (sorted according to priority):
- [ ] installation instructions on Windows and Mac
- [ ] getting-started with Hive
- [ ] feature description
- [ ] tutorials
- [ ] developer doc

using readthedocs.io? @daren-thomas what would you suggest? I noticed an existing `\doc` folder - is that a draft?

**Comment by ChrisZenhub** [comment]
@daren-thomas will make a framework

**Comment by daren-thomas** [comment]
I think the best solution is to use the GitHub wiki function. This will make editing the documentation as frictionless as possible. Also, "hive" is already a project on readthedocs.org :-(
