### ISSUE TITLE
use Linus' SIA demand model

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#414]
@daren-thomas is it possible to import @Linwal model into a Honey-Badger component? It uses numpy, would this be a problem for IronPython? As a workaround, could we turn Linus' model into an executable and then call it from a Honey-Badger component?

https://github.com/architecture-building-systems/sia_380-1-full_version

@Linwal would you have time for a short demo/intro of your model?

**Comment by ChrisZenhub** [comment]
closing as redundant. we are about to finish our hourly demand version with #586
