### ISSUE TITLE
visualizer form autoscale KPI buttons

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#416]
the top right buttons have a fix size. can we make their size dynamic in relation to the overall component size?

**Comment by daren-thomas** [comment]
short answer: not really... as this is based on the font size used to display the text. and using a font other than the standard font introduces other problems. like... how will the user be sure to be able to read everything?

so... what i'm going to do is figure out the wiggle room (what is the minimum size we can use) as well as figure out what the minimal height and with of the plots should be. that might help with the ugly rendering bugs.
