### ISSUE TITLE
UI / UX design for monthly irradiation for each window on GhVisualizer

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#419]
related issue #418

**Comment by daren-thomas** [comment]
@amraladdin connect with @christophwaibel what the data looks like.

**Comment by amraladdin** [comment]
[Solar Irradiation Plot_FIN.pptx](https://github.com/architecture-building-systems/hive/files/5276309/Solar.Irradiation.Plot_FIN.pptx)

Design checked w/ Christoph and Daren. Best of luck guys!
