### ISSUE TITLE
coding a plot for monthly irradiation on windows on GhVisualizer

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#420]
design done in #419

**Comment by ChrisZenhub** [comment]
@daren-thomas can you assume the data to be a `List<double[Misc.MonthsPerYear]>`, with each array in the list corresponding to a window of the building and implement that into `ResultsPlotter` ? Then, I'll plug in my data later

**Comment by daren-thomas** [comment]
@amraladdin please link the sharepoint powerpoint design here

**Comment by amraladdin** [comment]
https://systems.sp.ethz.ch/_layouts/15/start.aspx#/03Research/Forms/AllItems.aspx?RootFolder=%2F03Research%2FResearchProjects%2F26%5FHIVE%2FUI%5FUX%2FOutputs&FolderCTID=0x012000D04D58F24D4632499F9E9A495C2B3DED&View=%7BACAE4832%2D3B4A%2D43C9%2D905C%2D28FF8AF7A72A%7D

**Comment by amraladdin** [comment]
https://systems.sp.ethz.ch/03Research/ResearchProjects/26_HIVE/UI_UX/Outputs/Solar%20Irradiation%20Plot_FIN.pptx?d=wdc1c2bc43775451884e98d34150dd267

**Comment by daren-thomas** [comment]
@amraladdin I just noticed something I didn't think of in the meeting: The list you show at the bottom of the plot - we can't do that. The reason being, it's not a _form_, it's just a canvas. I'm going to just plot the bars for now.
