### ISSUE TITLE
Use separate UValues for Walls, Roofs, Floors

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/hive#421]
Currently, the BuildingInput form uses the same values for walls, roofs and floors. Before we add a catalogue of such elements for the user to choose from, we should change that. This refers to `Hive.IO.Forms.BuildingInputState`

- `.UValueOpaque`
- `.OpaqueEmissions`
- `.OpaqueCost`

Also, that should then be used to create appropriate `Construction` objects when `GhBuilding.SolveInstance`.

**Comment by ChrisZenhub** [comment]
resolved by #466?
