### ISSUE TITLE
getting copyright-ok images for solar technologies for Hive Energy Systems Form

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#424]
We need images that represent the different solar technologies. These images will be implemented into our Hive Energy Systems Input Form. 
Consider copyright, how? Just add a source/link beneath the image?

![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/6d378867-d3ea-4faf-a53c-9d5ee14f4bc4)

PV:
- Polycristalline
- Monocristalline
- CIGS
- CdTe
- HIT

Solar Thermal:
- vacume_tube
- flat_plate

**Comment by ChrisZenhub** [comment]
Hoi zäme

Hab auf dem Server Mal ein paar Fotos abgelegt:
\\nas22.ethz.ch\arch_ita_schlueter\01-Team\05-PersonalFolder\Larissa

**Comment by christophwaibel** [comment]
Larissa and Linus images:

\\nas22\arch_ita_schlueter\03-Research\01-Projects\26_HIVE\06_Development\_EnergySystems\Images
