### ISSUE TITLE
Add 3 new ingoing arrows in Sankey Diagram for Cooling Case

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#425]
in cooling case, ventilation and envelope transmission losses will be negative (? i think) from SIA380 component. This needs to be accounted for in the Sankey Diagram. To be consistent, in this case, arrows should move to the left, because they are Inflowing energy into the zone (hot air coming in), instead of out.

UPDATE: you will find 3 new properties in `ResultsPlotting.cs`:

```
        public float VentilationGains => (float) Results.TotalVentilationHeatGains;   
        public float EnvelopeGains => (float) Results.TotalOpaqueTransmissionHeatGains; 
        public float WindowsGains => (float) Results.TotalWindowTransmissionHeatGains; 
```

You will need to add 3 new arrows onto the sankey diagram that go IN to the building, so on the left hand size. Take the same colors as the Outgoing arrows for VentilationLosses, OpaqueTransmissionLosses and WindowTransmissionLosses

**Comment by ChrisZenhub** [comment]
@daren-thomas will need to code it in the Sankey Diagram, @christophwaibel will need to check the data first

**Comment by daren-thomas** [comment]
@daren-thomas wait for "go" from @christophwaibel
