### ISSUE TITLE
implement PV and ST images into EnergySystemsForm

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#431]

**Comment by ChrisZenhub** [comment]
blocked by #424

**Comment by ChrisZenhub** [comment]
design change @daren-thomas :
do not implement the building examples. Only implement the technology images. 

@amraladdin I hope you're ok with my decision.

**Comment by amraladdin** [comment]
@ChrisZenhub of course. Sounds good to me.
