### ISSUE TITLE
Sankey building diagram electricity input doesnt match output  

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#444]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/bc0fea0f-57c3-4071-983c-47095c9b82ad)

for calculating primary energy, we use primary energy factor of electricity times electricity loads. 
The difference to final electricity needs to be added to the system losses

**Comment by ChrisZenhub** [comment]
electricity fixed now.

but this here also needs to be considered:
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/cd5739a9-6f06-485b-8b1b-e0367629a018)

eta_g needs to be used to compute "system losses" for Q_S and Q_i .

But should it be attributed to system losses? eta_g is only partly describing the heating system, but mostly the building dynamics. See text above

**Comment by daren-thomas** [comment]
@christophwaibel is this what the PR #447 is about?
