### ISSUE TITLE
Provide brief text for solar technologies

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#449]
Write 2-3 sentences describing characteristics of solar technologies, focussing on what is relevant to architecture. (e.g. "thin film is good because you can bend and glue it no curved surfaces, but not as efficient as ... polycristalline..."... or similar. Of course, better formulations please :) 

Please send me the text as text or word file, we will implement it into the tool @hillias @Linwal .

- [x] PV Polycristalline
- [x] PV Monocristalline
- [x] PV CIGS
- [x] PV CdTe
- [x] PV HIT
- [x] ST vacuume tube
- [x] ST flat plate

**Comment by ChrisZenhub** [comment]
The text will appear here on the bottom left:
![Capture.PNG](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/4bb08024-0a7f-44fc-b17b-2d31c3d3f87c)

**Comment by christophwaibel** [comment]
[PV description.docx](https://github.com/architecture-building-systems/hive/files/5363958/PV.description.docx)

**Comment by ChrisZenhub** [comment]
[https://app.zenhub.com/files/110542628/8cf10703-862a-4d16-adb3-801e32943782/download](https://app.zenhub.com/files/110542628/8cf10703-862a-4d16-adb3-801e32943782/download)
