### ISSUE TITLE
Make an installl zip

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#450]
Amr is Test Baby.

Don’t forget oxyplot  and newtonsoft

**Comment by amraladdin** [comment]
Awaiting the ZIP :)

**Comment by ChrisZenhub** [comment]
[https://app.zenhub.com/files/110542628/194d7d42-94e3-446f-a2c7-f19575834692/download](https://app.zenhub.com/files/110542628/194d7d42-94e3-446f-a2c7-f19575834692/download)
[https://app.zenhub.com/files/110542628/cd0a1463-3199-4b94-aa8d-22da61b47230/download](https://app.zenhub.com/files/110542628/cd0a1463-3199-4b94-aa8d-22da61b47230/download)

@amraladdin please test on your pc and check if it runs. note that it is not the final version for the lecture yet

@daren-thomas newtonsoft is not needed for the users (yet), since no jsons are created within their workflow

**Comment by daren-thomas** [comment]
@christophwaibel newtonsoft is used for the serialization/deserialization of the hive results as a parameter type.

**Comment by ChrisZenhub** [comment]
[https://app.zenhub.com/files/110542628/64917adc-ccc9-4171-9fc2-1425dfcabb47/download](https://app.zenhub.com/files/110542628/64917adc-ccc9-4171-9fc2-1425dfcabb47/download)

final Hive files for E02 in Energy and Climate Systems 3, HS 2020

(does not include Daylight Factor files - those are Ladybug)
