### ISSUE TITLE
Wrong solar insolation calculation for some locations

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#453]
Something's wrong with the simple solar calculation `simple_panel.py` for some locations. It does work for european locations. Check out `simple_panel.gh` in Hive Core\solar.

Can't say exacactly yet, where the problem is... maybe a bug in my Blanco-Muriel algorithm implementation..?

**Comment by ChrisZenhub** [comment]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/a2a60cd1-8f4e-4ba3-a10e-5894f1b74474)

shift 8760 timeseries of solar vectors by the time zone, e.g. in this case time zone is -8, shift timeseries respectively

**Comment by christophwaibel** [comment]
fixed in original repo: https://github.com/christophwaibel/GH_Solar_V2/pull/37

**Comment by ChrisZenhub** [comment]
re-opening, because another PR is fixing this issue for Hive
