### ISSUE TITLE
Implement the editable option for honey-badger

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/hive#46]
Motivation: Development of the components will be much faster if we don't need to close/restart rhino+gh every time we make a change to the components.

honey-badger includes an "-e" option for "editable", a bit like how pip does it. This would create a ".ghpy" file that delegates to the original source (by reloading?) instead of including it outright. This still needs to be implemented.

**Comment by ChrisZenhub** [comment]
shouldn't this issue be in the honey-badger repository? @daren-thomas

**Comment by christophwaibel** [comment]
closing as outdated, since we are phasing out honeybadger for Hive
