### ISSUE TITLE
testing v1.0.0 and identifying bugs and things to improve

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#465]
using the current build and the 2 E02 exercise files, try out all kinds of things and note all bugs and things to improve

**Comment by ChrisZenhub** [comment]
- get feedback from the lectures

**Comment by amraladdin** [comment]
Seems it's working nicely. Here's the PPT Preview.
We can discuss about the results in our sprint meeting today. 
[HIVE_Testing.pptx](https://github.com/architecture-building-systems/hive/files/5422333/HIVE_Testing.pptx)
