### ISSUE TITLE
separate construction properties for walls, roofs, floors

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#466]
currently, they are treated the same, e.g. in the Building Form, changing one parameter in wall changes it too for roofs and floors

**Comment by ChrisZenhub** [comment]
add this feature when the drop downs get populated 

![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/5f4f30a2-6f9f-43a1-a57f-a7183ef443e7)
