### ISSUE TITLE
Create 3D Model templates

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/hive#47]
To vary in the different models:
- Number of floors [2, 3, 4, 5, 8, 12]
- WWR
- Context [No context, low-density, medium-density, high-density] refer to EaCSIII as a starting point.
- ...

**Comment by christophwaibel** [comment]
`...\26_HIVE\06_Development\0_Input_Geometry\Scenarios_templates.3dm`:
![image](https://user-images.githubusercontent.com/21927657/75273546-5dcaba00-5801-11ea-821d-93a4f41305c2.png)

**Comment by amraladdin** [comment]
Hello Christoph. Shouldn't we close this issue then and work with the three 3D Rhino models in the preview above?

**Comment by christophwaibel** [comment]
> Hello @christophwaibel . Shouldn't we close this issue then and work with the three 3D Rhino models in the preview above? Or should I create the same three shapes parametrized in GH?

hey @amraladdin , yes, a parametric model of them in grasshopper would be awesome! maybe also an option to change the roof type (flat, pitched, saddle) with parameters to change their height, or similar.

If I have a grasshopper file, it would be easier for me to later on hardcode it into a separate component, you know, your idea about the "automatic-template-building-generator"-script.

**Comment by ChrisZenhub** [comment]
issue outdated with current Hive design
