### ISSUE TITLE
make an .exe installer for Hive 1.3.0

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#475]
For the next release (for E03), make an installer that automatically installs all `.dll`, `.gha` and `.ghpy` files into the correct folder and also deletes old files.

Some files are renamed. See branch  https://github.com/architecture-building-systems/hive/tree/456-rehaul-GhComponents-descriptions

**Comment by ChrisZenhub** [comment]
@christophwaibel give @daren-thomas a list of files to be deleted and to be installed into which folder
