### ISSUE TITLE
Plan an experiment, including the A/S Chair members to test and give feedback on hive

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/hive#483]
Plan a quick workshop for A/S teams to test hive end of 2020. Perhaps early December?

**Comment by ChrisZenhub** [comment]
@amraladdin when should we do that? Maybe in June? 

What exactly needs to be tested and what kind of feedback do we want?

**Comment by ChrisZenhub** [comment]
closing as non-development related
