### ISSUE TITLE
figure out automated select survey 

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#496]

**Comment by ChrisZenhub** [comment]
@amraladdin sorry, what is automated select survey again?

**Comment by amraladdin** [comment]
Hello @ChrisZenhub , I was referring to being able to generate automatically, through SelectSurvey, scatter plots to study the correlation between the students' knowledge on Rhino/GH and the ease of using the tool/templates.

Update: I figured out there is no way to do this automation. The easiest way is to export a .CSV file and post-process it, which is what I've been working on this week.
