### ISSUE TITLE
wpf-forms-dont-open-for-some-users

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#500]
as the title says. here are the forum posts of EaCS3:

- https://moodle-app2.let.ethz.ch/mod/forum/discuss.php?d=62472#p128454
- https://moodle-app2.let.ethz.ch/mod/forum/discuss.php?d=62010
- https://moodle-app2.let.ethz.ch/mod/forum/discuss.php?d=63996

**Comment by ChrisZenhub** [comment]
maybe we need to directly zoom with the students and do live debugging? hard to reproduce the error otherwise.

Could it be that they need to install some .net windows extension, or similar? @daren-thomas

**Comment by ChrisZenhub** [comment]
suggestions to try out:

- sample wpf application (no rhino) and see if that runs
- open wpf dialogue from ghpython 
- try windows form component (in rhino grasshopper)

**Comment by daren-thomas** [comment]
Ueli has found a solution (separate desktop pc that works) and Michéle isn't answering any of my questions. Do we proceed to find the needle in the haystack or call it a day?

**Comment by ChrisZenhub** [comment]
@daren-thomas let's try: sample wpf application (no rhino)

**Comment by daren-thomas** [comment]
[https://app.zenhub.com/files/110542628/4b48255a-b975-4f43-b766-2ba79fc79875/download](https://app.zenhub.com/files/110542628/4b48255a-b975-4f43-b766-2ba79fc79875/download)

Zip includes the TestVisualizer.exe program. That should prove that WPF works on a given computer...

**Comment by daren-thomas** [comment]
To test with GhPython:

- copy "Hive.IO.gha" to "Hive.IO.dll" in the Libraries folder. 
- create a GhPython component, edit the contents (double-click to open the editor)
- add the following script:

```
import clr

clr.AddReference("Hive.IO")

import Hive.IO.Forms
form = Hive.IO.Forms.EnergySystemsInput()
form.ShowDialog()

print("done.")
```

- press "Test" - you should see the Energy Systems Input dialog...

**Comment by daren-thomas** [comment]
The branch `500-add-logging-to-forms-double-click-event-handler` contains extra debug output (using `RhinoApp.WriteLine`) for the `GhBuilding` component. Test like this:

- copy the `Hive.IO.gha` ([https://app.zenhub.com/files/110542628/1e1b3fe8-700e-4ebe-9694-f625aa84d7c4/download](https://app.zenhub.com/files/110542628/1e1b3fe8-700e-4ebe-9694-f625aa84d7c4/download)) to the Grasshopper Libraries folder, replacing the original one from Hive
- open the `Hive_Workflow_Full.gh` file from the examples folder
- double-click the "HiveInputBuilding" component. Close the dialog.
- check the Rhino command output. You should see the following:

```
GhBuilding.ShowUIClick - ENTERED
GhBuilding.ShowUIClick - _buildingInputState != null
GhBuilding.ShowUIClick - form created
GhBuilding.ShowUIClick - before form.ShowDialog()
GhBuilding.ShowUIClick - after form.ShowDialog()
GhBuilding.ShowUIClick - form.ShowDialog() returned
GhBuilding.ShowUIClick - form.State.SiaRoom saved
Traceback (most recent call last):
  File "hblib_3b4dd266_f7e0_4614_aef5_cadf1e3319d2", line 115, in SolveInstance
  File "simple_panel", line 61, in main
TypeError: expected float, got NoneType

GhBuilding.ShowUIClick - END
```

**Comment by daren-thomas** [comment]
@christophwaibel I think this covers most of the points we need to debug the problem a bit more. Would you mind reaching out to the students with this?

**Comment by christophwaibel** [comment]
> https://app.zenhub.com/files/110542628/4b48255a-b975-4f43-b766-2ba79fc79875/download
> 
> Zip includes the TestVisualizer.exe program. That should prove that WPF works on a given computer...

well, even my computer doesn't like this exe

![image](https://user-images.githubusercontent.com/21927657/100471542-c7eaf500-30da-11eb-97b3-afa3da81e89b.png)

**Comment by ChrisZenhub** [comment]
- let Students try the new GhVisualizer double click axis windows form dialogue. if that works for them, let's transition from WPF to windows form (boooo!)
