### ISSUE TITLE
design honeybadger solar component icons

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#506]
Currently, lot's of smileys 
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/d2865f5e-7e21-476e-9da1-96d002420588)

**Comment by lillaa** [comment]
[_iconsszusammen.png](https://images.zenhubusercontent.com/5ec10bebe045932b9a6b3ebd/4a11079e-edba-472d-aedb-1630847a688c)

[https://app.zenhub.com/files/110542628/07847252-3fce-4e29-ba3b-a1b6fb61679f/download](https://app.zenhub.com/files/110542628/07847252-3fce-4e29-ba3b-a1b6fb61679f/download)!
