### ISSUE TITLE
Results - Create dedicated Results saving and Results distributor components

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#511]
This issue is on creating a proper Results component in Hive that replaces a current ghpython script

![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/385c50c5-b1e3-4a34-bf54-767712f4c523)

https://github.com/architecture-building-systems/hive/issues/308#issuecomment-730394457

## Proposal

Dropdown list to choose which aspect of results to take out

**Comment by ChrisZenhub** [comment]
issue #604 "export data into a csv / json etc" could be part of this issue

**Comment by ChrisZenhub** [comment]
UX:
the component should have 2 inputs:
- Hive Results object
- a string indicating what kind of output we want (heating loads, cooling loads, solar potentials, etc...). That string comes from a separate list component that has all possible strings (i.e., all possible outputs from the hive results class) baked into it

As a first prototype, make it these 2 components (results reader and list component) for those outputs that the [ghpython component in the .gh template file](https://github.com/architecture-building-systems/hive/releases/download/v1.13.1/EaCS3_E04_Hive_Template_debugged.gh) has. (see image below)

![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/42315e36-dabe-4313-8a6b-9b165f47d068)

**Comment by ChrisZenhub** [comment]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/8bd9d934-44bd-484a-9e9e-2719a2ec2460)

could also have multiple inputs to specify the desired output

**Comment by maxenceryan** [comment]
due to complexity, limiting this issue to a dropdown of which result to extract, no filter. New issue for filtered distributor will be created
