### ISSUE TITLE
variable tau value in sia380 model for thermal latency

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#516]
Currently, we have tau constants from sia 2024 that implicitly represent thermal latency of a construction. Let us make it variable based on construction heat capacities and surface areas!

https://miro.com/app/board/o9J_leSAuA0=/

<img src="https://render.githubusercontent.com/render/math?math=\tau=\frac{CA}{H_{\text{T}}+H_{\text{V}}}">

**Comment by ChrisZenhub** [comment]
related to #587

**Comment by ChrisZenhub** [comment]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/28a42e94-c755-40df-b831-1be79a9044a5)

from the EuKS Formelsammlung

**Comment by maxenceryan** [comment]
per discussion:
- use SIA 2024 values for now per floor area
- eventually would be good to apply heavy/medium/lightweight specific heat capacities for different building elements in hizard via dropdown
  - SIA 380
    - lightweight: 50
    - mittel: 100
    - schwer: 150
  - [Approximated from DIN EN ISO 13786](https://wiki.energie-m.de/Wirksame_W%C3%A4rmekapazit%C3%A4t#:~:text=F%C3%BCr%20einen%20detaillierten%20Nachweis%20nach,wirk%20%3D%20%CE%A3%20%CF%87i%20*%20A)
    - leichte Gebäudezonen Cwirk = 50 Wh/(m²K) * ANGF
    - mittelschwere Gebäudezonen Cwirk = 90 Wh/(m²K) * ANGF
    - schwere Gebäudezonen Cwirk = 130 Wh/(m²K) * ANGF

**Comment by maxenceryan** [comment]
per discussion
- in the end we will take specific heat capacity per floor area from SIA 380 (as above, with superlightweight at 10wh/m2K)
- update hizard on SIA panel to select construction type, propogate to all components for now

**Comment by maxenceryan** [comment]
per discussion:
- check if tau is equal based on values in SIA 2024
- Building construction type on main tab
- remove capacities on envelope
- room specific heat capacity on the main tab
- make use of uvalues walls and floors and roofs
- surface_type in sia380 should be window/roof/wall/floor instead of opaque/transparent (GhSIA distributor)
