### ISSUE TITLE
update Hive PV catalogue

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#521]
Update the PV technologies catalogue in the Energy Systems Hizard:

![image](https://user-images.githubusercontent.com/21927657/135135090-5bf82c09-e714-4d75-9286-9270c0363190.png)

That includes:
- [x] reviewing existing module types and if necessary removing / adding tech
- [x] remove HIT PV from catalogue, because it is actually proprietory (Panasonic?) (https://miro.com/app/board/o9J_leSAuA0=/)
- [x] update parameters (module efficiency, spec embod emissions, spec capital cost, tech description

Database to be worked on: 
- `.../src/Hive.IO/Hive.IO/Resources/pv_efficiency.csv` (tech parameters)
- `.../src/Hive.IO/Hive.IO/Resources/EnergySystems` (images)
- `.../src/Hive.IO/Hive.IO/EnergySystems/surface_tech_module_types.json` (contains the current descriptions. Could you add a `Description` column to the `pv_efficiency.csv` above and add a string there? Note: no need to edit this `.json`, because there should be a script that creates it based on the `csv`) 
- `.../src/Hive.IO/Hive.IO/Resources/Sources.docx` (document your references used in this file)

**Comment by christophwaibel** [comment]
@maxenceryan does the `build.cmd` include re-compiling the `json`, too? If not, could you add it to the build cmd?

**Comment by maxenceryan** [comment]
@christophwaibel the `build.cmd` script does include all JSON generators, but this one is not generated. I will add it though once it is ready (done in #655)

**Comment by maxenceryan** [comment]
- descriptions were added as part of pending PR #657
- I'd recommend adding sources to the Sources.md (should be in the same directory...) as well, since this is easy to open with any text editor and not proprietary :). I've also tried to assemble all sources there that are spread a little everywhere, and feel free to edit it to your liking
