### ISSUE TITLE
add honey-badger functionality to change list component icons

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#535]
```
{
      "class-name": "Sia2024RoomList_Standard",
      "name": "SIA 2024 Standard Rooms",
      "abbreviation": "Sia2024RoomsStandard",
      "description": "A list of SIA 2024 rooms, standard building quality",
      "category": "[hive]",
      "subcategory": "Demand",
      "id": "8903e11e-abba-4318-a9b2-6728e2999652",
      "parameter-type": "ValueList",
      "csv": "..\\..\\Hive.IO\\Hive.IO\\Resources\\201008_SIA2024_Raumdaten_Standardwert.csv",
      "icon": "sia2024_room_creator.png"
    }
```

honey-badger can be compiled without error, but the icon is not shown in Grasshopper yet. This issue is about adding this functionality to Honey-Badger

![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/7a8e39c6-bfb5-47ed-91f4-88ae0b6a18dc)

**Comment by daren-thomas** [comment]
![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/303b3056-7010-4473-8125-2ac8f9069cae)

The newest version of honey-badger implements this now. See the planets example for how to set the icon for a ValueList parameter.

**Comment by daren-thomas** [comment]
@christophwaibel mind checking this please?

**Comment by christophwaibel** [comment]
@daren-thomas works!

![image](https://user-images.githubusercontent.com/21927657/101501569-31d38c00-3970-11eb-8e98-8ebbac0a342a.png)
