### ISSUE TITLE
orientation factor

### ISSUE THREAD

**Issue by hillias** [architecture-building-systems/hive#54]
Create component based on data:
[https://app.zenhub.com/files/110542628/6b8b4849-3c34-4506-aca7-a32de61a9b96/download](https://app.zenhub.com/files/110542628/6b8b4849-3c34-4506-aca7-a32de61a9b96/download)

Input:
Location (default: Zurich)
Orientation (default: south)
Tilt (default: 0 (horizontal)
Month (default: January)

Output:
OF (%)

**Comment by daren-thomas** [comment]
@hillias is this still a thing?

**Comment by hillias** [comment]
![image](https://user-images.githubusercontent.com/40200288/72887719-89dbb280-3d0c-11ea-83d9-8dbafdf82d02.png)

**Comment by christophwaibel** [comment]
How it works:
(1) read in .epw.
(2) compute solar radiation for a location (using our solar model), unobstructed, and for different angles/orientations.
(3) Orientation factor is 100% on a flat surface. Then, the % for the other angles can be computed.
(4) The visualizer shoudl be able to output OF for the entire year, for seasons, and for individual months. See Illias picture above.

**Comment by christophwaibel** [comment]
related issue: https://github.com/architecture-building-systems/hive/issues/83

**Comment by hillias** [comment]
Reference/Lecture notes for PV calculation including performance ratio etc. (see slide 30ff)
[EuKS2_2_ErneuerbareEnergieerzeugungGebäude.pdf](https://github.com/architecture-building-systems/hive/files/4103059/EuKS2_2_ErneuerbareEnergieerzeugungGebaude.pdf)

**Comment by hillias** [comment]
Performance ratio is highly dependent on shadowing (which might be influenced by season), see for example 
![image](https://user-images.githubusercontent.com/40200288/72985272-e959c100-3de5-11ea-9359-7408615ce14b.png)
Source: https://ieeexplore.ieee.org/abstract/document/8366633
Linus might have better data on this.
