### ISSUE TITLE
Hive-version info

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#547]
Similar to Ladybug/Honeybee, add these little black tags beneath each Hive component that informs on the current version:
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/cbb31080-6d4d-45b5-a947-e73dae5f8cad)

**Comment by ChrisZenhub** [comment]
for now, only add to Hive main distributor: 

![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/71b5d00b-58d8-46fd-8416-aeef74443e62)

**Comment by philipschulz** [comment]
@ChrisZenhub this is done very easily via the Message property :) is there a proper versioning system for Hive components right now? Displaying the assembly version doesn't seem quite right 
![image.png](https://images.zenhubusercontent.com/6177bbd62b89e7f9c066d805/163407d6-2adc-49ce-bfb2-5a978442a80e)

**Comment by christophwaibel** [comment]
@philipschulz ah nice!
no, not really. Can you propose a system? It should correspond to the release tags (https://github.com/architecture-building-systems/hive/releases), e.g. 1.3.1

**Comment by christophwaibel** [comment]
Yes sounds reasonable. Add it also to the PR-template checkboxes (Debugging artifacts, update template file, ..., update assembly version number)
