### ISSUE TITLE
Window surface component causes error when connected to the "HiveInputBuilding" Component  

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/hive#556]
When connecting Window surfaces to the "HiveInputBuilding" Component, the component generated the error in the below picture:
![image.png](https://images.zenhubusercontent.com/57b431eee40e5714b16d74ed/b2955c94-5909-470c-a823-d45bfeec1bc0)

I tried:
- Redrawing the windows, checking for their planarity on the bloc -> doesn't work.
- Connecting only one surface. -> Doesn't work, regardless which surface is connected.
- Checking the "Dir" command. -> Surfaces Normals are oriented correctly (i.e. outwards).

The only way the "HiveInputBuilding" Component  works and the simulation runs, is by disconnected the window. See the Testing files attached.
[https://app.zenhub.com/files/110542628/e724dd89-1813-4c52-8a13-5156a19f92f5/download](https://app.zenhub.com/files/110542628/e724dd89-1813-4c52-8a13-5156a19f92f5/download)

**Comment by ChrisZenhub** [comment]
I believe this was solved by #561, right @amraladdin ?
