### ISSUE TITLE
Some icons on Wiki need updating

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/hive#559]
For example:

![image.png](https://images.zenhubusercontent.com/57b431eee40e5714b16d74ed/bc21e40f-3c8f-42b8-84b1-8332bca0dea3)

current logo:

![image.png](https://images.zenhubusercontent.com/57b431eee40e5714b16d74ed/993853a1-7034-4138-9238-1006735eef95)

**Comment by ChrisZenhub** [comment]
done by @maxenceryan
