### ISSUE TITLE
Fix the heat recovery from solar and internal gains factor so that the calculation can work for cooling cases as well as heating cases

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/hive#56]
Fix the heat recovery from solar and internal gains factor so that the calculation can work for cooling cases as well as heating cases.
- [x] Check which standards (probably SIA 382-2, which is about acclimatizing buildings). It's on the server, but in German.
- [ ] See if there's an equation.
- [ ] Ask Linus for help.
- [ ] Ask Saso to incorporate in hive.

**Comment by ChrisZenhub** [comment]
@amraladdin to which "calculation" does this issue refer to? Could you specify?
