### ISSUE TITLE
Consider SIA 2024 schedules for demand calculation (sia380 component)

### ISSUE THREAD

**Issue by maxenceryan** [architecture-building-systems/hive#565]
## Problem

Heat gains from occupancy, lighting and equipment are currently provided as total hours in a year. Although one can average out these hours for monthly calculations, hourly  demand simulations need hourly schedules of when these internal gains occur.

Also applies for electrical demand

## Proposal

- Creating mapping table for SIA 2024 space usage to schedules for occupancy, lighting, appliances
- Encode the schedule into a more compressed form rather than 8760 values
  - compressing values might speed up grasshopper runtime
  - 24 values for each day type (weekday, weekend, holiday), day type for first day of year (e.g. "monday"), indices for holidays
  - 8760 --> 24*3 + 1 + about 15 holidays = 88 values
  - Recreate hourly profile inside components if needed
  - look at energy plus to see how they do schedules?
- Add this encoded schedule in the room properties JSON
- Implement in sia380 component

**Comment by ChrisZenhub** [comment]
-> lighting demand schedules? SIA 387/4? not sure

**Comment by ChrisZenhub** [comment]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/509da65d-27cf-4f82-b643-aac4b1bd043d)
