### ISSUE TITLE
Add natural ventilation to reduce cooling demand in SIA 380 module

### ISSUE THREAD

**Issue by maxenceryan** [architecture-building-systems/hive#567]
Currently the hourly version of SIA 380 seems to greatly overestimate cooling demand vs monthly. Upon viewing hourly values, it seems it was indicating cooling demand even if outdoor temp was significantly lower than the indoor temp.

Realistically, someone would open windows, and therefore natural ventilation could be considered and substracted from cooling demand.

Some equations exist for this, but require more input (dimensions of openings, maybe ambient pressure but could probably due without) into the module and may be too detailed
- for open doors and windows, V_dot = c_d * A * sqrt(2/density * delta_pressure). c_d = 0.6 for open windows, A is area, density = density of air at given temp.
- for rectangular openings,V_dot = c_d * H * W / 3 * sqrt(g * H * (T_i - T_e)/T_e) which relies on height width and temperatures only. This would be easier to use but would require knowing the dimensions of the windows, not just the areas.

**Comment by ChrisZenhub** [comment]
when implementing this into ``sia380.py'' we need to make sure that natural ventilation can be easily switched off. This is to keep the didactic purpose of Hive as a teaching tool. E.g., a student could check a checkbox in the building form for natural ventilation and thus study the impact that has on energy demand.

**Comment by maxenceryan** [comment]
per discussion:

- use rectangular openings calc for now as relies only on temperature
- we will sqrt the area to derive the height dimension

**Comment by maxenceryan** [comment]
could be helpful https://www.priceindustries.com/content/uploads/assets/literature/engineering-guides/natural-ventilation-engineering-guide.pdf

**Comment by maxenceryan** [comment]
current progress

Notice sliiiight differences in this summer week esp when T_e climbs to be equal to T_i_lb (mornings around 10am or so), which would assume that heat gains when T_e is reaching that lower bound can be removed better with nat vent than mechanical vent. Otherwise not terribly effective.

Could be because:
- we only consider buoyancy driven nat vent (not wind driven, which might be far more effective)

without nat vent
![image.png](https://images.zenhubusercontent.com/5d38d5318f4bde000110956b/dfcf012f-7f21-4340-bd3b-3a72c03acf0a)

with nat vent

![image.png](https://images.zenhubusercontent.com/5d38d5318f4bde000110956b/0ffa2a8a-3835-4b56-98fe-fcb359109c14)

**Comment by maxenceryan** [comment]
todo:
- check results against intuition, What do we expect to happen over a summer/winter/spring day w.r.t.  natural ventilation?
- solve no windows bugs as a bonus
