### ISSUE TITLE
Corner windows not recognized by buildings form

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#580]

**Comment by ChrisZenhub** [comment]
**Cases that need to be fixed**
- edge window:
![grafik.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/f4e94e12-fe4e-431f-b8f5-2a275ef47a1a)

- corner window:
![grafik.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/0bcc9806-42eb-4a42-88dc-702e98844fb3)

- 2 edge windows touching; error message will say they intersect:
![grafik.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/607c4acd-c220-4a77-879e-f71dd3a37e3d) 

- polygons and other shapes should also work:
![grafik.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/44a3aba6-6fa7-4eb9-b76f-e815b9fc2308)
