### ISSUE TITLE
validate sia 380 demand component 

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#589]
compare our sia380 component, monthly / hourly, with, e.g., BESTest, and see how our model performs with other energy simulation programs.

also compare with @Linwal demand model

try it with a simple box building?

**Comment by maxenceryan** [comment]
shoebox 5x5x3m created and applied to following cases:
- hive
- SIA 380 created in A/S chair
- Honeybee + EnergyPlus

Details about modelling differences to be documented...

Initial results

**Comment by maxenceryan** [comment]
related #95

**Comment by Linwal** [comment]
@maxenceryan My data is normalized by area, so it is kWh/m2

**Comment by maxenceryan** [comment]
aaah of course, my bad. I should have realized this.

Comparison looks much better now 
- green = Hive
- blue = Honeybee
- red  = SIA380

@christophwaibel also a few corrections from earlier:
- this is indeed MONTHLY, not aggregated hourly (I missed the TODO in the earlier comment)
- uses adaptive comfort
- before there was some null Q_s feeding in so now it is running using the unobstructed solar simulation.

![image.png](https://images.zenhubusercontent.com/5d38d5318f4bde000110956b/f16307dc-8a29-4fdc-bc3a-e5fe5480036c)

**Comment by christophwaibel** [comment]
well, this validation study is complete. Closing therefore.
