### ISSUE TITLE
Energy Systems Form does not show PV images

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#591]
In the new windows forms, the PV images are not showing up. This was working in the older WPF forms

now:
![image](https://user-images.githubusercontent.com/21927657/121241977-51565d80-c89c-11eb-9839-e8031a218b21.png)

before:
![image](https://user-images.githubusercontent.com/21927657/121242201-92e70880-c89c-11eb-884f-35ddef0bf434.png)

**Comment by maxenceryan** [comment]
Suspected culprit in  `Hive.IO.Forms.ConversionTechPropertiesViewModel`:

```cs
        public ImageSource TechnologyImage => IsSurfaceTech
            ? new BitmapImage(new Uri(
                $"pack://application:,,,/Hive.IO,Culture=neutral,PublicKeyToken=null;component/Resources/EnergySystems/{ModuleType.Name}.jpg"))
            : null;
```

Might just be about redoing the resource linking.
