### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by JustinZarb** [architecture-building-systems/hive#6]
I already implemented the unit tests in the main branch of RC_Buildingsimulator in grasshopper, where scenarios are described using dictionaries. 

1. The dictionary system could be implemented in the original unit tests, which are hard to transfer.

2. The unit tests should be repeated for the 'zone2' component, which is a lightly modified version of the Building class in building_phyics.py

**Comment by ChrisZenhub** [comment]
closed as outdated
