### ISSUE TITLE
Introduce "cancel" and "ok" instead of cross - hive building input "ENHANCEMENT" 

### ISSUE THREAD

**Issue by Lementi** [architecture-building-systems/hive#603]
I'd suggest to introduce a **cancel** and **ok** button for the hive.building input (hizard I Building) (and the other windows as well), since GH restarts calculating when one closes the window, which can be very annoying, if one only wants to check values or look something up.

**Comment by maxenceryan** [comment]
Thanks for the feedback! @christophwaibel maybe we could use a false start toggle on the user friendly side of the gh script, similar to how many ladybug/honeybee scripts do it? Otherwise having some global "re-run" variable could be tricky...  Or some run toggle in the HiveInputs component

**Comment by nkobylinska** [comment]
> Thanks for the feedback! @christophwaibel maybe we could use a false start toggle on the user friendly side of the gh script, similar to how many ladybug/honeybee scripts do it? Otherwise having some global "re-run" variable could be tricky... Or some run toggle in the HiveInputs component
> 
> there is an option with [caching](https://www.grasshopper3d.com/forum/topics/avoid-recompute-the-component-when-change-a-parameter) if nothing changes in the hizard, but im not such a big fan of this as to propogate to all the components sounds a bit chaotic.
> 
> easiest workaround is simply to disable the Main hive distributor when adjusting params.
> 
> ![image.png](https://camo.githubusercontent.com/a052a70ca6e9b8c9131332d429385df29e579044c8c3a46f1ac41be9a14ea6e5/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3564333864353331386634626465303030313130393536622f34346132333262332d633361612d343366382d393965302d626465643636346635313434)

I also think a toggle would be handy from a user's perspective, in HB it works super nice :)

**Comment by ChrisZenhub** [comment]
@maxenceryan proposition: Hive mothercell could have a radio-button for on/off, similar to Diva

**Comment by ChrisZenhub** [comment]
I can see 2 workflow situations:

A) manual design, changing some inputs. Here, a boolean button on the mothercell `update simulation` would make sense that the user needs to press before calculations in the core are initiated
B) parametric / automated workflow, e.g., optimization or sensitivity analysis. Here, a boolean toggle `always update simulations` would make sense, so you don't have to press the button from A) all the time

this needs a UI Design proposition first, before it can be coded up

**Comment by ChrisZenhub** [comment]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/74220ba6-00cd-446e-aed9-bbc0ab74bcd0)

Let us just allow it to get a boolean toggle for now and if its on false, it won't run the core
