### ISSUE TITLE
Build SIA JSON resources upon building installer

### ISSUE THREAD

**Issue by maxenceryan** [architecture-building-systems/hive#605]
Compile the SIA 2024 data and schedules as part of build script.

compile_sia2024_json.py
generate_sia2024_schedules_json.py
build.cmd

**Comment by christophwaibel** [comment]
`build.cmd` doesn't seem to build honey-badger components properly? example, `sia380.json` didn't get build

**Comment by maxenceryan** [comment]
after deleting all build files and all libraries from grasshopper foldder, then rebuilding via `build.cmd`, still seems to work for me. so will merge and if bug persists open new issue.
