### ISSUE TITLE
Bug/Error: Tree Output from Hive Distributor Component

### ISSUE THREAD

**Issue by justinfmccarty** [architecture-building-systems/hive#608]
Hello, QC testing Hive using the example files right now. As I was trying to engage the right part of the first example I came across a bunch of NoneType Errors on the various reader components: 
<img src="https://user-images.githubusercontent.com/44881937/123411501-d043d980-d5b0-11eb-835d-4d1b29ec58f9.png" width=50% height=50%>

I worked around by flattening the the input to these components and then taking the first item in that list:
<img src="https://user-images.githubusercontent.com/44881937/123411662-f9646a00-d5b0-11eb-833f-c3396be6b219.png" width=50% height=50%>
See these files: 

GH - https://www.dropbox.com/t/BRXvkkILCkv6kUEQ
3DM - https://www.dropbox.com/t/YDFZUJdAsB8cNlN4

**Comment by ChrisZenhub** [comment]
This bug can be avoided when the inputs to the main distributor are flattened:
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/cb5b2bac-0aa3-4c0f-b909-a1905a23cbb2)

It's something we need to ensure in the template files.

Therefore, closing this issue
