### ISSUE TITLE
Results display error 

### ISSUE THREAD

**Issue by Vpiccioni** [architecture-building-systems/hive#612]
When running the script for the first time, I got a series of display errors as in the Screenshots. 
![Grasshopper display error 2](https://user-images.githubusercontent.com/69684278/123453475-e452ff80-d5df-11eb-9412-afe959601656.PNG)
![Grasshopper display error](https://user-images.githubusercontent.com/69684278/123453477-e4eb9600-d5df-11eb-86a6-4d844ab2b22e.PNG)

Error is solved after uninstalling and re-installing HIVE. Not sure what the problem was!

BUG

**Comment by maxenceryan** [comment]
Closing as reinstalling seemed to work.... added this general tip in the [Troubleshooting wiki page](https://github.com/architecture-building-systems/hive/wiki/Troubleshooting)
