### ISSUE TITLE
Shading mask does not change with location of building

### ISSUE THREAD

**Issue by TianjiaoYang** [architecture-building-systems/hive#616]
[ShadingMask.zip](https://github.com/architecture-building-systems/hive/files/6725508/ShadingMask.zip)
Hi there,

I was testing out the shading mask functionality from Exercise 2. However the shading mask hemisphare is always gray/black regardless of where I position my building box. Please see attached files.

I am using a newer version, namely Rhino 7. I don't know if that is the reason.

Keyword: BUG

Best, 
Tianjiao
![1](https://user-images.githubusercontent.com/55989746/123623438-b94df300-d80d-11eb-8923-f929f99b4fa7.png)
![2](https://user-images.githubusercontent.com/55989746/123623441-b9e68980-d80d-11eb-8b46-b2cbc27c08eb.png)
![3](https://user-images.githubusercontent.com/55989746/123623443-ba7f2000-d80d-11eb-9609-0301805b68af.png)

**Comment by maxenceryan** [comment]
Thanks Tianjiao! We tried to provide [a solution here](https://github.com/architecture-building-systems/hive/wiki/Troubleshooting#shading-mask-dome-for-solar-calculations-is-all-obstructed) but it may not be sufficient. if you have time let me know if that resolves it :)

Related / possible duplicate #602

**Comment by TianjiaoYang** [comment]
> Thanks Tianjiao! We tried to provide [a solution here](https://github.com/architecture-building-systems/hive/wiki/Troubleshooting#shading-mask-dome-for-solar-calculations-is-all-obstructed) but it may not be sufficient. if you have time let me know if that resolves it :)
> 
> Related / possible duplicate #602

![image](https://user-images.githubusercontent.com/55989746/124135229-e86d9a00-da83-11eb-99fa-c3ff7dac632f.png)
![image](https://user-images.githubusercontent.com/55989746/124134830-84e36c80-da83-11eb-9a58-8ca0a6e59e0a.png)


Hi Max,
unfortunately, no. I'm moving the sensor point way above, but it's still the same gray dome. 
Also I had a look at the shading mask component. It seems the context input does not include the building geometry, so I suppose the building itself should not shade the sensor point, i.e. should not black out the shading mask?
Let me know if there's anything else I can do to help.

**Comment by christophwaibel** [comment]
Hi @TianjiaoYang , thanks for reporting this. That is a Rhino 7 rendering bug. When adding an explicit mesh component to the Skydome component, it will render again:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/21927657/148914200-f0644033-d2d0-481c-90cf-982bfe6ed384.png">

Fixing it in the main Grasshopper template for the next release
