### ISSUE TITLE
Editing y-axis range on visualizer is unintuitive

### ISSUE THREAD

**Issue by lillaa** [architecture-building-systems/hive#618]
Hi

You probably know this. The y axis of the energy demand chart is not fixed and changes according to the highest value (which also make sense, I understand). However, for me, as a user that was the most disturbing, that I don't have an option to fix it (or I just didn't find it). It makes it impossible to compare alternatives correctly.

**Comment by ChrisZenhub** [comment]
Hi @lillaa ,
thanks for noticing this! We actually already have a feature implemented that you can fix the axis: Simply double click anywhere on the Y-axis and it will open a new window, where you can specifiy the axis range. 

But I reckon, this should be made more obvious, e.g., by highlighting the axis when the mouse hovers over it

![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/a82d5552-2a7f-410f-b322-04c90f84e94f)

**Comment by ChrisZenhub** [comment]
closing as redundant. however, it is unintuitive. #529 to address this
