### ISSUE TITLE
Hive building input form not large enough in Envelope tab

### ISSUE THREAD

**Issue by TianjiaoYang** [architecture-building-systems/hive#623]
![image](https://user-images.githubusercontent.com/55989746/123645776-e955c000-d826-11eb-951f-7eb588803cd8.png)

Hi,

as shown in the screenshot, the dialog for defining the building properties is not big enough to accommodate all the information, and I was not able to expand the window nor scroll down. 

Besides, it was not very intuitive that a double-click on the component gives this dialog box, without reading an additional documentation (like the one we receive with the exercises), so it would be nice if such instruction is also in the GH template (like a scribble text or something)

Keyword: ENHANCEMENT

**Comment by maxenceryan** [comment]
What operating system / rhino version did you use for this? Is the operating system in a non-english language? The font usually appears different so it may be either missing on your machine and causing this cutting off... Something we should take into account.

Also good tip about documenting the double click, thanks!

**Comment by TianjiaoYang** [comment]
> What operating system / rhino version did you use for this? Is the operating system in a non-english language? The font usually appears different so it may be either missing on your machine and causing this cutting off... Something we should take into account.
> 
> Also good tip about documenting the double click, thanks!
![image](https://user-images.githubusercontent.com/55989746/124132012-a98a1500-da80-11eb-9a69-5759b4bb4c60.png)
![image](https://user-images.githubusercontent.com/55989746/124132332-ff5ebd00-da80-11eb-94d4-f78a32f4e6a8.png)

Hi Max,
thanks for the reply. I do have English as the system language, and I'm using Rhino Version 7 SR6 (7.6.21127.19001, 2021-05-07) on a Windows 10 OS, see attached images. Hope that helps.

**Comment by ChrisZenhub** [comment]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/e446bf67-60fd-4e13-a479-36d3d0ff4e1b)

I'm having the same problem. What is weird is that in the visual studio form designer, it is large enough:
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/7bf89973-0f35-463c-bfe7-8cf6a2f6f2fc)

**Comment by ChrisZenhub** [comment]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/a54c0fa8-9a2e-417b-99bf-f22fc799a4ca)

there is just a mismatch between designer and how it actually looks like...

made it bigger anyhow: 
1005d76
