### ISSUE TITLE
Add Warning Message on EnergySystems Hizard on missing surface allocation

### ISSUE THREAD

**Issue by Vpiccioni** [architecture-building-systems/hive#625]
Understanding how to select PV surfaces within the Input Energy systems component is not straightforward. Selecting/referencing mesh components in Rhino is not sufficient, they also need to reference in the Input form (screenshot 2). For me, this second step was not obvious, and I thought the PV panels were not being considered due to bad geometrical definition (surface normal, etc...).

Maybe the user interface of the solar system could be improved in this sense and state clearly that the surfaces need to be selected?
![PV surfaces selection](https://user-images.githubusercontent.com/69684278/123648775-8580c680-d829-11eb-8d26-7c47ac61ff93.PNG)
![PV surfaces selection_2](https://user-images.githubusercontent.com/69684278/123648790-86b1f380-d829-11eb-9600-3999483ac9c1.PNG)

ENHANCEMENT

**Comment by ChrisZenhub** [comment]
to do: 
- when there are un-assigned surfaces in the EnergySystems Hizard, the component should spit out a warning message: 

´Note: There are connected surface geometries that have not been assigned to any solar enery technology:
Surface1
Surface3
Surface4
...
´

https://developer.rhino3d.com/api/grasshopper/html/M_Grasshopper_Kernel_GH_ActiveObject_AddRuntimeMessage.htm
