### ISSUE TITLE
Rhino 7 keeps crashing when doing solar simulation

### ISSUE THREAD

**Issue by TianjiaoYang** [architecture-building-systems/hive#629]
![image](https://user-images.githubusercontent.com/55989746/123651823-1789ce80-d82c-11eb-806d-5e4e795cbe3c.png)
![image](https://user-images.githubusercontent.com/55989746/123651847-1bb5ec00-d82c-11eb-867c-99f87c2f9401.png)
[ThisCrashes.zip](https://github.com/architecture-building-systems/hive/files/6726962/ThisCrashes.zip)

Hi,

unfortunately my Rhino model keeps crashing when I try to do solar simulation (step 8 of exercise 1). It could be because I'm using Rhino 7, or it could also be because my computer is pretty old. I attach the files and some specs of my computer if that helps. 
I did manage to run solar simulation for 1 or 2 times, but only without PV included.

Keyword: BUG

**Comment by ChrisZenhub** [comment]
works on @mmatache25 ...
@philipschulz give it a try
@christophwaibel gives it a try

if it works on all our computers, close

**Comment by ChrisZenhub** [comment]
works on my mac parallels rhino 7. However, I could identify 2 bugs related to the solar simulation out of this example file:
#713 #714

Closing
