### ISSUE TITLE
check correctness of KPI values in Visualizer

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#632]

**Comment by ChrisZenhub** [comment]
Make sure the numbers of the KPI buttons at the top right of the Visualizer are correct.

I'm not sure, if the calculations were all correct or if those are dummy numbers

**Comment by maxenceryan** [comment]
Update

- Emissions now set up with operational and embodied in amr plot. yay 
- defaults for specific chiller costs are 0.0 chf/kw (in the conversion tech default json), which is weird. is there a source we could use, maybe from CEA?
- do the carrier costs / emissions take into account the primary energy factor?
