### ISSUE TITLE
Visualizer solar gains show total value

### ISSUE THREAD

**Issue by lillaa** [architecture-building-systems/hive#636]
Hi, Beim solaren Wärmeeintrag könnte man vielleicht auch den Totalwert auch irgendwo anzeigen.

**Comment by ChrisZenhub** [comment]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/99c25598-d7ef-44d7-a5a7-2cadab0810ab)

something like that. Top left corner, show sum of all solar gains.
