### ISSUE TITLE
Setting axis titles removes the function to auto set to min and max range

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#638]
**Describe the bug**
You can set the axis ranges in the hizualizer. By default, the range is max and min of the data. But once you set the range manually, there is no way to activate auto min max again. This should be somehow possible!

**To Reproduce**
1. Open a working Hive template
2. go to the hizualizer and change the axis range
3. be sad that there is no auto min max anymore

**Expected behavior**
There should be a way to re-activate auto min max range

**Screenshots**
![image](https://user-images.githubusercontent.com/21927657/125838676-3f2c0dfb-813c-41e9-982d-a3d3ad7c2215.png)

**Comment by ChrisZenhub** [comment]
related issue #618

**Comment by philipschulz** [comment]
@ChrisZenhub 
![image.png](https://images.zenhubusercontent.com/6177bbd62b89e7f9c066d805/afa0c2cb-b0a3-4332-b423-56133a3d639f)
With a button like this?

**Comment by christophwaibel** [comment]
Sounds good !

**Comment by philipschulz** [comment]
Should clicking the button instantly reset the axis, or only apply the reset once the Save button is clicked?

**Comment by christophwaibel** [comment]
Only upon clicking on the save button

**Comment by christophwaibel** [comment]
But the text fields should already be cleared when clicking reset. Maybe they could even display the numeric auto min max values?
