### ISSUE TITLE
WP02_Tool Design and Concept

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/hive#65]
Main objective is the design of the overall solution consisting of the software collaboration and matching tool as well as the integration with other tools.

It contains an explanation of the tool purpose, defines the scope and development methodology (such as Agile or Scrum) and techniques are explained as do the main players and contacts.

**Comment by christophwaibel** [comment]
our concept so far:
https://github.com/architecture-building-systems/hive/blob/master/repository_files/00_Hive_Architecture.jpg

**Comment by daren-thomas** [comment]
this is hive.
