### ISSUE TITLE
Wiki - Add Validation section for reference

### ISSUE THREAD

**Issue by maxenceryan** [architecture-building-systems/hive#659]
> “Validation”, maybe between “Developer Doc” and “Legacy Pages”, and then show [this graph](https://github.com/architecture-building-systems/hive/issues/589#issuecomment-876319902) and put the pulled-out idf, gh file and epw. Also, a few words describing the validation case (shoebox, Hive version, …)
>
> The “Validation” section of the Wiki could be structured in Monthly Loads, Solar Potentials, for now. For the solar potentials, could you write a sentence that it has been validated with Daysim, EnergyPlus and Radiance and further information can be found here: https://doi.org/10.1016/j.solener.2017.10.054

**Comment by christophwaibel** [comment]
nice, thanks!

@Linwal , your SIA380 repo is currently set to Private. Do you plan making it public in the future?
