### ISSUE TITLE
WP03_Development and Iterative Adaptations

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/hive#66]
The development environment will be the sandbox of the development team. That’s why it won’t be stable at all times, and you can expect data inconsistencies.

The main objective is to transform the calculation models into Python scripts and GH components. Develop prototypes and usable  manuals and concepts for the pilot testing phase. End of this phase should be the development of the full set of the Innovedum proposal tools.

**Comment by daren-thomas** [comment]
this is hive and [hive:process]
