### ISSUE TITLE
KPI Visualizer unclear

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#667]
**Describe the bug**
It is unclear to users what the KPIs in the visualizer calculate. Currently, they compute 
- primary energy consumption over the building lifetime
- total emissions over the building lifetime
- total costs over the building lifetime

**Expected behavior**
The energy KPI would be more intuitive as an annual value, not for the building lifetime. For consistency, emissions and costs should also be showing annualized values. The user may him/herself then multiply this value by the expected building lifetime.
A tooltip when hovering over the respective KPI would also help.

**Screenshots**
![image](https://user-images.githubusercontent.com/21927657/141002777-25c8a377-593c-4250-a975-88d25a88c9f8.png)

**Software**
 - Hive Version 1.13.1

**Comment by ChrisZenhub** [comment]
@christophwaibel tell @philipschulz strings for each of the tooltip buttons on the visualizer
