### ISSUE TITLE
SIA Room Parametric Input should read in geometry

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#681]
Parametric input component needs to be able to read Hive.Building geometry, so only thermal properties are replaced with slider values. Right now, also geometric properties need to be input as numeric values, but that way we loose relevant information such as window orientations (for solar calculations)

![image](https://user-images.githubusercontent.com/21927657/144272203-b137b2f4-4238-4010-97ae-08e7e65c9325.png)

**Software**
 - Rhino Version 6
 - Hive Version 1.3.1

**Comment by ChrisZenhub** [comment]
To Do:
- remove parameters `floorArea, envelopeArea, glazingArea`. These should always be coming from real geometries, directly connected to the Building Hizard. Therefore, this parametric input component should only parse all other parameters into the Building Hizard, except spatial parameters.
- if the building hizard has a parametric input component connected to it, it will take over these parameters. This is already implemented, but it also copies floor, envelope and window areas, which should always be read from real rhino geometry
