### ISSUE TITLE
Draw colorbar onto RhinoViewport for Solar Simulation

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#690]

**Comment by ChrisZenhub** [comment]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/5f5e6631-ec24-4f8f-a3b8-c67387ea8f49)

![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/20667bcd-cb09-4a2f-8cf8-cfa0cef448e4)

When running solar simulations, a drawn colorbar onto the Rhino viewport would help. Currently, a user would have to manually draw a colorbar

**Comment by ChrisZenhub** [comment]
probably should be developed in the original solar repo https://github.com/christophwaibel/GH_Solar_V2

**Comment by philipschulz** [comment]
@ChrisZenhub What was the decision again last friday, original solar repo or in Hive repo?

**Comment by christophwaibel** [comment]
there was no decision. you wanted to have a look at the solar repo first and decide if it is feasible to implement it there. But there were some concerns that that repo might be a little messy to understand as an external person

**Comment by ChrisZenhub** [comment]
@christophwaibel give @philipschulz a gh file with several windows and PVs to check out how it looks with lots of curves

**Comment by ChrisZenhub** [comment]
@philipschulz to do: add conduit dll and gha into setup folder (similar to the solad model) and add its installation to build.cmd

**Comment by christophwaibel** [comment]
> @christophwaibel give @philipschulz a gh file with several windows and PVs to check out how it looks with lots of curves
[LotsOfWindowsAndPVs.zip](https://github.com/architecture-building-systems/hive/files/9085946/LotsOfWindowsAndPVs.zip)

@philipschulz here you go

**Comment by ChrisZenhub** [comment]
@philipschulz as per discussion:
- check license for conduit
- daily sum of all windows, instead of separate curves per window
- installer, check for existing conduit.gha
