### ISSUE TITLE
Monthly and Annual Demand | SIA 380-1

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/hive#70]
Calculate monthly and annual demand using SIA 380-1

- we have a basic SIA 380.1 monthly component already
- extend with auxillary components to make using SIA 380.1 easy
- calculate yearly demand

**Comment by christophwaibel** [comment]
https://github.com/architecture-building-systems/hive/blob/master/sia380/sia2024.py existing

now only missing sia2028 for climate data (irradiation and ambient temperature)

**Comment by christophwaibel** [comment]
https://github.com/architecture-building-systems/hive/tree/master/Core/sia380
