### ISSUE TITLE
refactor Results Merger

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#707]
the results merger has separate inputs for ideal loads (heating, cooling, electricity) at the very top. Currently, heating gets its values from a custom ghpython component that substracts building loads according to our SIA demand calculator from solar thermal (or other) renewable heat production. This should be refactored in a way that we have inputs as pure building loads and pure supply. The plots in the visualizer and the results merger should take care of proper post-processing

**Comment by ChrisZenhub** [comment]
... that also means that the Visualizer Demand plot needs to have renewable energy generation added as new bars (that point downwards). Also, better have a stacked bar plot?:

![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/5e18572a-dff0-48f3-aa60-9f615c30538e)

**Comment by christophwaibel** [comment]
there needs to be a separate issue on re-designing the Visualizer, respectively, what the plots show.
