### ISSUE TITLE
Review and possibly migrate Hive.Core\sia2024_room:_creator.py

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#710]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/a9c64584-1957-48a9-9b89-4bea1d9835f0)

- review if this component is still necessary. With everything being in the same c# project, we don't need to (de-)seriaize jsons anymore
- if we need this component, migrate it to c#
- remove from `build.cmd` and `hive.nsi`
- test correctness between c# and honeybadger components

**Comment by ChrisZenhub** [comment]
we don't need this anymore, we have the parametric building input component #708
@christophwaibel remove from setup, then close this issue

**Comment by philipschulz** [comment]
@christophwaibel Parts of this already exist made by Max in Hive.Core.sia380 as well as the C# code to build SIA2024 Json objects from the inputs. Should I finish this task? Shouldn't take more than ~2-3h if nothing unexpected pops up

**Comment by ChrisZenhub** [comment]
nothing needs to be done here. deactivate later in #706 
- `Hive.Core.sia380.gha` and `ghpy` in `hive.nsi`
- `sia380.json` in `build.cmd`
