### ISSUE TITLE
WinForm add manual resizing

### ISSUE THREAD

**Issue by justinfmccarty** [architecture-building-systems/hive#718]
**Describe the bug**
I had a student in the Hive course report an error in their EnergySystemInputForm where they could not see the dropdown menu to set the PV type. In order to replicate their bug I had to resize my screen from my standard 1920x1080 at 100% zoom to a smaller setting. (see screenshots)

**To Reproduce**
1. Go to Display Settings
2. Change your screen to 1440x900 or similar and 125% scaling.
3. Open the Input Form for Energy Systems.
4. You will not be able to 

**Expected behavior**
The form selection menu should appear despite the zoom level on the screen.

**Screenshots**
See two screenshots.

**Software**
 - Rhino Version 7.14
 - Hive Version 1.10.2

**Additional context**
If possible, being able to resize these form windows dynamically would solve this problem. This feels like it is an error bordering on an Accessibility issue for users that require a large zoom on their screen or are not able to access larger screens.
![Screenshot 2022-01-24 114939](https://user-images.githubusercontent.com/44881937/150770278-6ac782d5-7927-49ca-9f15-1315d31e1b2e.png)
![Screenshot 2022-01-24 114615](https://user-images.githubusercontent.com/44881937/150770284-23fb0ad5-9aac-41a3-b460-e899c925c42b.png)

**Comment by ChrisZenhub** [comment]
Yes, it should be relatively easy to add a manual sizing option to our 2 WinForms (Building and Energy Systems forms)
