### ISSUE TITLE
Energy Systems BIPV duplicate technologies

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#727]

**Comment by ChrisZenhub** [comment]
There are duplicate technologies in BIPV:

![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/d16a55ad-f82f-44d8-b6c4-c691296de63b)

**Comment by ChrisZenhub** [comment]
... and we can't read the full text. When mouse hover-over, after a second, it should display the full text

**Comment by mmatache25** [comment]
The technologies are defined this way in the JSON file. To be checked and closed.
@christophwaibel

**Comment by mmatache25** [comment]
- not duplicates but different colours based on different energy efficiencies
- tooltip over surface transmittance to choose the color
- update the CSV 
- "duplicate technologies" only have one color per technology

@justinfmccarty please update CSV file

**Comment by justinfmccarty** [comment]
@mmatache25 What would you like changed in the CSV?

**Comment by christophwaibel** [comment]
@justinfmccarty per discussion, please rename the names in the `Type` column to make it clear what technology it is (red, steel, green, etc...). And we will keep the full list

**Comment by christophwaibel** [comment]
@mmatache25 it actually is a bug. The efficiency (and other) parameters are not changing in the EnergySystems hizard, no matter which BIPV Tech is selected

those should be two different items with different efficiencies:
![image](https://user-images.githubusercontent.com/21927657/166701095-3e2f5252-b52c-48af-8e46-63b6dc82d52f.png)

![image](https://user-images.githubusercontent.com/21927657/166701135-5a5562e6-e3f6-4dc3-bbcb-1cc1e8764def.png)

**Comment by christophwaibel** [comment]
> * not duplicates but different colours based on different energy efficiencies
> * tooltip over surface transmittance to choose the color
> * update the CSV
> * "duplicate technologies" only have one color per technology
> 
> @justinfmccarty please update CSV file

@mmatache25 Tooltip string when hovering over `Surface Transmittance` text box on the Hizard: "Parameter to control the transmittance through the cell covering layer - \"Durchlassgrad der Zellabdeckung\" (German)"
