### ISSUE TITLE
Tooltip or Extend String on EnSys Combobox

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#737]

**Comment by ChrisZenhub** [comment]
The updated energy systemts hizard has a BIPV and PV comboboxes with quite long strings that don't get fully displayed when selected.

we need to find a solution to show the full string

**Comment by christophwaibel** [comment]
![image](https://user-images.githubusercontent.com/21927657/172617343-7dd7946b-cad0-44b4-b14a-2df094966c55.png)

**Comment by christophwaibel** [comment]
@mmatache25 can you also remove the word "integrated" from each of the list items? Then, it's at least a little shorter
