### ISSUE TITLE
Add tables / data feature to honey-badger

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/hive#74]
A lot of the components we're creating use lookup-tables (think Excel files) to base calculations on.

How could these be incorporated into hive? Currently, the data needs to be hardcoded in a component as a list or a dictionary. Instead, allow specifying a file as data and have that shipped inside the component or something (as a resource?). Or at least automate the creation of lookup-tables. A bit like what we do for the badger-config.

handle these formats:

- csv: Result either in rows of dicts or columns of arrays
- xlsx: Result is a dict of worksheets, each like the csv

also, how could the end-user pass in their own data?

**Comment by christophwaibel** [comment]
Honey-badger: value lists that read .csv files
.Net: embedded .csv files in the .dll / .gha

manual overwrite in Rhino via our Hive.IO windows forms
