### ISSUE TITLE
Visualizer crashes when RunHive False

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#747]
**Describe the bug**
The visualizer "crashes" when having the "Solar Gains per Window" plot activated and then switching off the Core (Run Hive = False). Switching on the toggle again will resolve it though, but still, the error message is scary.

**To Reproduce**
1. Open the main template `Hive_FullTemplate.gh`
2. Set the toggle `Run Hive` to `True`
3. Switch the visualizer plot to `Solar Gains per Window`
4. Switch off the Run Hive toggle to `False`
5. Be sad about the display error

**Expected behavior**
No error message and no crashed visualizer.

**Screenshots**
Step 1-3, all good:
![image](https://user-images.githubusercontent.com/21927657/178312594-6ae7485e-2c37-4bad-8514-7558863c414d.png)

Step 4, not good:
![image](https://user-images.githubusercontent.com/21927657/178312646-922c698d-db2b-4a21-887c-296250c373aa.png)

**Software**
 - Rhino Version 6
 - Hive Version 1.5.x (current master)

**Comment by philipschulz** [comment]
@christophwaibel could not reproduce...

![image.png](https://images.zenhubusercontent.com/6177bbd62b89e7f9c066d805/9b078496-70d0-4f2e-8856-2895c5e52300)

**Comment by christophwaibel** [comment]
@philipschulz all other plots are also fine? If so, then close it as solved :)

**Comment by pedrammrbn** [comment]
Also tested on mine.

![image.png](https://images.zenhubusercontent.com/6363ca4e212714ee9a67c42e/87094c2b-647c-43eb-9b48-7bb85a2b608a)
