### ISSUE TITLE
draw surface normals on all windows and walls and roofs

### ISSUE THREAD

**Issue by ChrisZenhub** [architecture-building-systems/hive#762]

**Comment by ChrisZenhub** [comment]
![image.png](https://images.zenhubusercontent.com/5e72694300eea37d1acdc3c6/1406cab8-260b-4dcd-990a-f06ef0185cba)

**Comment by ChrisZenhub** [comment]
as per discussion: "what if window centroid coincides with wall centroid"?
-> hardcode threshold to check coinciding centroids, if yes, randomly move one arrow away, 
-> assign different drawing properties to windows and walls (e.g., dashed vs solid lines, etc.)
-> ..?

**Comment by ChrisZenhub** [comment]
careful with the grasshopper example above; it turns it into a mesh and then we might have multiple centroids per surface.
-> better directly work with original surface. (careful: untrimmed vs trimmed surfaces)

**Comment by philipschulz** [comment]
![image.png](https://images.zenhubusercontent.com/6177bbd62b89e7f9c066d805/1425738c-3be7-49b6-b2d2-bb9880281d03)
this does it
