### ISSUE TITLE
Tooltip colour KPI visualizer

### ISSUE THREAD

**Issue by christophwaibel** [architecture-building-systems/hive#772]
**Tooltip colour KPI visualizer**
The colours of the KPI are a bit colourful :-) Can we change it to the same colours as the 3 KPI boxes, just with a slight transparency?

**Screenshots**
![image](https://user-images.githubusercontent.com/21927657/192167296-2a839a84-4e01-4e56-97c1-febcc07c395e.png)

**Software**
 - Hive Version 1.16

**Comment by philipschulz** [comment]
![image](https://user-images.githubusercontent.com/16674735/222229602-ae4766a0-90ff-4b03-8f9b-444eb7ca17b1.png)
@christophwaibel so?

**Comment by christophwaibel** [comment]
yes! @philipschulz
