### ISSUE TITLE
Icons for new Components

### ISSUE THREAD

**Issue by philipschulz** [architecture-building-systems/hive#776]

**Comment by philipschulz** [comment]
Some new components being introduced need icons:

- Conduit Distributor
- 3d arrow data distributor
- 3d arrow vector calculation
- 3d arrow display

**Comment by philipschulz** [comment]
Some new components being introduced need icons:

- Conduit Distributor
- 3d arrow data distributor
- 3d arrow vector calculation
- 3d arrow display

**Comment by ChrisZenhub** [comment]
related issue #700

**Comment by ChrisZenhub** [comment]
idea: use conduit pngs but change color with photoshop
