### ISSUE TITLE
Reproduce demand validation study

### ISSUE THREAD

**Issue by pedrammrbn** [architecture-building-systems/hive#786]

**Comment by pedrammrbn** [comment]
Reproduce Bombyx and hive demand, compare results with validation study
https://github.com/architecture-building-systems/hive/wiki/Validation

**Comment by christophwaibel** [comment]
https://moodle-app2.let.ethz.ch/pluginfile.php/1453230/mod_folder/content/0/CompECD_L07_Sensitivity_Energy.gh?forcedownload=1

it just occured to me, you can also look at our CompECD ghpython implementation

**Comment by pedrammrbn** [comment]
Comparison of the three methods: Hive, Bombyx Demand, and the SIA model.
Bombyx demand was almost double the other two, Hive and SIA values are close.
The area for Hive is multiplied by 0.9, which also slightly affects the difference.

![image.png](https://images.zenhubusercontent.com/6363ca4e212714ee9a67c42e/001bf26a-5e49-4958-be40-41c9f63f2acf)

**Comment by pedrammrbn** [comment]
@AlinaGalimshina @ChrisZenhub Here are the Rhino+GH files if you also want to take a look!
[Uploading... Validation & Comparison.3dm]
[Uploading... Validation & Comparison.gh]

**Comment by pedrammrbn** [comment]
https://polybox.ethz.ch/index.php/s/XxMyddUCk7WxAyI

**Comment by christophwaibel** [comment]
https://github.com/architecture-building-systems/hive/wiki/Validation

added to the Hive Wiki, and will add Validation data to a new folder... validation data...?

**Comment by christophwaibel** [comment]
https://github.com/architecture-building-systems/hive/tree/master/tests
