### ISSUE TITLE
Building Lifetime

### ISSUE THREAD

**Issue by pedrammrbn** [architecture-building-systems/hive#804]
How is the building's lifetime defined? The value appears to currently be 80 but is not part of the information passed on in the SIA 2024 room object.  It would be beneficial to be able to see and override the value as part of the building inputs form.

![image](https://user-images.githubusercontent.com/108935429/214590764-76019035-2103-44b7-8601-1e7be6783ac7.png)

**Comment by christophwaibel** [comment]
closing as duplicate of #743
