### ISSUE TITLE
Results Object Read-only

### ISSUE THREAD

**Issue by pedrammrbn** [architecture-building-systems/hive#805]
Hive.IO.Results.Results is read-only, preventing override from Bombyx.

**Comment by christophwaibel** [comment]
because it is better if the bombyx results feed into the Results merger (the component that writes the Hive.Results).

It might need a special "Bombyx-Merger" component to format bombyx data into something that fits into the "Results merger"

**Comment by christophwaibel** [comment]
closing per discussion. See issue #789
