### ISSUE TITLE
Design how the components fit together

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/hive#82]
How do all the various components from WP03 fit together? What are the interfaces for the various components? How do they "click" together?

The magic of hive will be proportional to "composability" of the components. Think lego. Sure, not all pieces will be 4x2, but that doesn't matter, because 2x2, 2x1 and 1x1 pieces are all compatible with 4x2 pieces.

Ideally, start playing around with "mockups". Create a gh file with "fake" ghpython component that just show inputs/outputs and different ways of (re-)using components.

**Comment by christophwaibel** [comment]
The Mothercell concept:
https://github.com/architecture-building-systems/hive/blob/master/README.md
