### ISSUE TITLE
PV Simplified Monthly calculation

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/hive#83]
- [x] Search for the EaCSIII's GH PV Simplified Calculation set.
- [x] Create a second issue and tag the component in it. Assign to Saso and ask to translate into Python.

**Comment by christophwaibel** [comment]
https://github.com/architecture-building-systems/hive/pull/109 @amraladdin

**Comment by christophwaibel** [comment]
@amraladdin can we close this issue?

**Comment by amraladdin** [comment]
Yes, I believe we can.
