### ISSUE TITLE
SubTask 04

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/hive#88]
Here are a bunch of things to consider for hive development:

- Connection to other tools and platforms
- LCA (Guillaume H.)
- Economics (Guillaume H. + CEA)
- Simplified Structural Analysis (Philip Block)
- COMPAS

(let's create separate issues for this epic when we get there)

**Comment by ChrisZenhub** [comment]
These tools could be used as stand-alone tools within our Mothercell Cluster

**Comment by ChrisZenhub** [comment]
outdated
