### ISSUE TITLE
Create a to build, install and test all the components in hive

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/hive#93]
honey-badger, of course! Update it to understand the following switches:

- `-m`, `--make`: instead of a badger-file, accept a project-root to scan for badger-files and build them
  - when used with the `-`, `--install` option, also install them to the Grasshopper components library
- `-t`, `--test`: expect either a badger-file or a project-root (in which case, scan for all badger-files and then test each one): for each component in the badger-file, look for the corresponding test file (see #91) and run all the tests. Complain if no tests found (yes. we're going to run tests on every. single. component!)

**Comment by christophwaibel** [comment]
closing as outdated, honeybadger being phased out for Hive
